### ISSUE TITLE
Add media content to methods with media upload

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#10]

**Comment by tcoffee-google** [comment]
Still need to fix this for other languages, correct? Did we finalize our draft for Java?

**Comment by tcoffee-google** [comment]
Placeholders added in #507, #538, #539.

@vchudnov-g suggests a further intermediate step of providing code hints for languages requiring additional method parameters: https://github.com/googleapis/toolkit/pull/542#discussion_r81231528

**Comment by saicheems** [comment]
Is this fixed?

**Comment by tcoffee-google** [comment]
Not yet. The eventual goal is to provide effective sample code. Current placeholders just link to external documentation.

**Comment by eoogbe** [comment]
@pongad Is this still relevant?

**Comment by pongad** [comment]
@saicheems Could you resolve if this has been finished?
