### ISSUE TITLE
Update proto comment regexes to match unordered lists

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1033]
### What

The comment fixers (e.g., https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/py/PythonSphinxCommentFixer.java) don't handle Markdown unordered lists correctly. They seem to be mis-recognized as code blocks.

### Example

proto: https://github.com/googleapis/googleapis/blob/af42d585cfd43537fc21f3e950b1db2210e0cd9e/google/logging/v2/logging_config.proto#L245

GAPIC:
https://github.com/lukesneeringer/api-client-staging/blob/c6e2da47cc3ed03305ac84506eefbeea6d614394/generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/config_service_v2_client.py#L411

**Comment by eoogbe** [comment]
This appears to be resolved
