### ISSUE TITLE
Allows dynamic values in baseline test.

### ISSUE THREAD

**Issue by shinfan** [googleapis/toolkit#1034]
PR reference: https://github.com/googleapis/toolkit/pull/1029

We need to support dynamic values in the baseline tests so that every time we bump up the version we do not need to update the baseline.

**Comment by eoogbe** [comment]
@saicheems I'm not following the importance of this. If the baseline tests are dynamic, are they still baseline? Maybe we should replace tests that depend on versions with unit tests.

**Comment by saicheems** [comment]
Yeah I'm not sure it makes sense to support dynamic values in baselines. Unit makes more sense.
