### ISSUE TITLE
Go method samples should be in a unique package

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#105]
`NewClient` should be called on the package name so users can copy paste code. The issue right now is the generator doesn't know the full import path.

**Comment by jba** [comment]
Copy/paste is a high bar. Usually when Go programmers read snippets and
examples, they understand that those are part of the same as the package
being documented, and they adjust.

If you want to support copy/paste, you may not be able to use the Example
feature of Godoc.

**Comment by pongad** [comment]
@jba Is it? Examples that I've seen seem to be in their own packages, like https://golang.org/pkg/strings/#example_Contains . Did I misunderstand you?

**Comment by jba** [comment]
I didn't know about this feature (near the end of https://golang.org/cmd/go):
"The entire test file is presented as the example when it contains a single
example function, at least one other function, type, variable, or constant
declaration, and no test or benchmark functions."

**Comment by saicheems** [comment]
Any strong opinion on this?
The functionality is there for the test to import the actual package, so I can implement if there's consensus.

**Comment by jba** [comment]
OK, found the key line in the doc of the go command: 'Test files that declare a package with the suffix "_test" will be compiled as a separate package, and then linked and run with the main test binary.'

So do that. Also search in https://golang.org/cmd/go/ for "An example function" and follow the rules there. 

You should end up with copy/paste-able examples integrated into the godoc.
