### ISSUE TITLE
Resource names as strings in APIs

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#1066]
In a few places we're calling ToString on resource names in generated snippets.
I suspect that this may be due to a poor configuration in some places. As an example, for Spanner the CreateSession method accepts a string rather than a DatabaseName:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.V1/Google.Cloud.Spanner.V1/SpannerClient.cs#L569

... so we end up with a snippet like this:

```csharp
SpannerClient spannerClient = await SpannerClient.CreateAsync();
// Initialize request argument(s)
string formattedDatabase = new DatabaseName("[PROJECT]", "[INSTANCE]", "[DATABASE]").ToString();
// Make the request
Session response = await spannerClient.CreateSessionAsync(formattedDatabase);
```

We clearly know enough about the field's format to do that much - why is the parameter for `CreateSessionAsync` not a `DatabaseName` itself? Is there ever a reason it should still be a string?

**Comment by chrisdunelm** [comment]
This is due to incomplete resourcename configuration in the relevant gapic.yaml.
We need to find all configs where resource_name_treatment is not STATIC_TYPES and complete the configuration.

**Comment by chrisdunelm** [comment]
https://github.com/googleapis/googleapis/issues/278 filed, which lists all GAPIC configs and methods with incomplete resource-name configurations.
So closing this issue.
