### ISSUE TITLE
Add Unavailable to list of codes to retry for non-idempotent calls

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#1080]
I believe this should just be a case of editing https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/configgen/RetryGenerator.java#L46

We may want to investigate other statuses as well:

- Internal
- Unknown
- DataLoss

**Comment by eoogbe** [comment]
@jskeet Can you add a priority to this?

**Comment by jskeet** [comment]
Assigned P2 to it, but I believe we first did it and then *undid* it after further discussion. @garrettjonesgoogle does that sound right to you? If so, we can just close.

**Comment by garrettjonesgoogle** [comment]
@jskeet - I believe you are correct.

- Your commit to add UNAVAILABLE: https://github.com/googleapis/googleapis/commit/b01f986d341005ee0c98ac3d3af764d974715091
- Your commit to remove UNAVAILABLE: https://github.com/googleapis/googleapis/commit/e6f2d2b99e28f40ad827e23d0b27ce2242705c40

https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/configgen/transformer/RetryTransformer.java currently does not add any codes for non-idempotent methods.

Thus, closing this issue.
