### ISSUE TITLE
[C#] Incorrect snippet initialization type for repeated resource-name fields

### ISSUE THREAD

**Issue by chrisdunelm** [googleapis/toolkit#1085]
Snippets are being generated with incorrect initialization code for repeated resource-name fields.

Example: `IEnumerable<BookNameOneof> optionalRepeatedResourceNameOneof = new List<string>();`
This should be: `IEnumerable<BookNameOneof> optionalRepeatedResourceNameOneof = new List<BookNameOneof>();`

**Comment by chrisdunelm** [comment]
[InitCodeTransformer.cs line 415](https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/transformer/InitCodeTransformer.java#L415) is where the wrong type is used to generate this snippet initialization code.

Instead of `item.getType()`, the `TypeRef` needs to be a repeated of the resource-name type.
It's not clear to me if this `TypeRef` is available or can be constructed.
Or if an alternate way of building/representing repeated resource-name types is required.

**Comment by chrisdunelm** [comment]
@garrettjonesgoogle, @michaelbausor if you or someone else who is familiar with this `InitCodeTransformer` code could have a quick look I would appreciate it. Thanks.

**Comment by garrettjonesgoogle** [comment]
I think @michaelbausor should take a look first since he is the most familiar with this at the moment.

**Comment by michaelbausor** [comment]
@chrisdunelm You are right, the existing logic is not correct for C# - in Java we use `new ArrayList<>()` so the type is not required in the repeated field case.

I will have a look now and propose a fix for the C# case.
