### ISSUE TITLE
travis fails due to missing protoc

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#11]
I've introduced .travis.yml but it fails on unrelated points.

As I take a look, the failure happens because it fails to find 'protoc' command from the commandline path.

17:13:09.331 [DEBUG] [TestEventLogger] io.gapi.vgen.JavaCodeGeneratorTest > library[java_settings] FAILED
17:13:09.331 [DEBUG] [TestEventLogger]     java.lang.IllegalArgumentException: proto compilation failed with internal error: Cannot run program "protoc": error=2, No such file or directory
17:13:09.331 [DEBUG] [TestEventLogger]         at com.google.api.tools.framework.model.testing.TestConfig.compileProtos(TestConfig.java:261)
17:13:09.332 [DEBUG] [TestEventLogger]         at com.google.api.tools.framework.model.testing.TestConfig.<init>(TestConfig.java:97)
17:13:09.332 [DEBUG] [TestEventLogger]         at com.google.api.tools.framework.model.testing.ConfigBaselineTestCase.test(ConfigBaselineTestCase.java:143)
17:13:09.332 [DEBUG] [TestEventLogger]         at io.gapi.vgen.JavaCodeGeneratorTest.library(JavaCodeGeneratorTest.java:57)
17:13:09.332 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:13:09.332 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:13:09.332 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:13:09.332 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by pongad** [comment]
One way to fix this is to create a setup script for travis to download from https://github.com/google/protobuf/releases . If I'm looking at this correctly, the problem is TestConfig relies on the system's protoc, not the one from build.gradle.

BTW, I'm a Travis newbie, how did you get the log?

**Comment by jmuk** [comment]
Right, TestConfig checks PROTOC_COMPILER environment variable or falls back to system protoc command. Downloading the binary might be good. But if we could reuse the one downloaded by gradle, that might be better?

For the detailed logging, I actually don't know the right way. I set up travis for my personal fork and put ./gradlew test --debug there (see https://github.com/jmuk/toolkit/commit/993a76b338dcd06455e9246fa7cf1a76f338d874 and https://travis-ci.org/jmuk/toolkit/jobs/125072582).

**Comment by tbetbetbe** [comment]
👍  for downloading using gradle

I notice that [build.gradle](https://github.com/googleapis/toolkit/blob/master/build.gradle) already takes a dependency on protobuf-gradle-plugin.   Hopefully, this can be solved by updating build.gradle as described in the [plugin readme](https://github.com/google/protobuf-gradle-plugin#locate-external-executables)

**Comment by pongad** [comment]
I think the problem is the protoc dependency declared on build.gradle "belongs" to the gradle tool, not normally accessible to the code gradle is compiling. That said, I'm unfortunately not familiar enough with Gradle to say for sure.

I looked into how the plugin finds protoc: https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L356 . The protoc seems to be a property of the project. If we use the one Gradle gets, we'll need a way to pass the property into the test.

**Comment by jmuk** [comment]
Fixed.
