### ISSUE TITLE
NodeJS: tests for streaming methods with errors fail

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#1108]
Through the regeneration of spanner API, I've met unit test failures for `invokes executeStreamingSql with error` and `invokes streamingRead with error`.

The real reason for this is a misunderstanding on nodejs handling. In short, it turns out that `mockStream.write()` is invoked earlier.

- for normal `'data'` events, the written data is queued, and the data events are emitted for the first time a listener is registered.
- on the other hand, the `'error'` event is different. When an error event happens but no error listeners are registered, it throws the error instead (see https://nodejs.org/api/events.html#events_error_events)

Because of this, `mockStream.write()` needs to happen after the error event listener is registered.

Possibly the diffs would be:
- remove `mockStream.write()` from `mockServerStreamingGrpcMethod`
- since `on` returns itself, `write()` can be added as:
```diff
       client.streamingRead(request).on('data', function(response) {
         assert.fail();
       }).on('error', function(err) {
         assert(err instanceof Error);
         assert.equal(err.code, FAKE_STATUS_CODE);
         done();
-      });
+      }).write();
```

**Comment by shinfan** [comment]
Our users will not append the `write` method to their method calls. Will this cause any issue in the production environment?

**Comment by jmuk** [comment]
Technically this is not in production since the generated tests are not running in CI, but it fails when I run them manually on api-client-staging repository.

Regarding `write`: that's fair enough. In that case maybe we want to switch the design back to the original one -- I remember that originally `mockStream.write()` was placed at the end of the each test case but I recommended to move into the common `mockServerStreamingGrpcMethod` in a PR.

**Comment by jmuk** [comment]
I've also noticed that we could simply delay calling `mockStream.write()`. This means to replace `mockStream.write()` by `setTimeout(function() { mockStream.write(); }, 0);`
