### ISSUE TITLE
go: forward in grpc.CallOption

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#1114]
cc @jba , sorry I lost track of this

Some APIs will need to specify grpc.CallOption to get gRPC header and trailer from the RPC call.
The easiest way to deal with this is probably to change the surface from
```go
GetShelf(ctx context.Context, req *librarypb.GetShelfRequest) (*librarypb.Shelf, error)
```
to
```go
GetShelf(ctx context.Context, req *librarypb.GetShelfRequest, opts ...grpc.CallOption) (*librarypb.Shelf, error)
```

@saicheems @jmuk what do you think?

**Comment by saicheems** [comment]
Well, it was once like this. Wasn't there a way to pass options as a property of the context?

It was something like
```
ctx.WithValue(opt)
```

**Comment by pongad** [comment]
@saicheems Are you referring to [this](https://golang.org/pkg/context/#WithValue)? That is useful for passing things into the request. But now we need to take the header/trailer set by the server *out* of the response. The mechanism to do this with gRPC-generate client is documented [here](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#unary-call).

Perhaps you meant users should place `grpc.CallOption` in the header, and we can pull it out then make RPC call with it? I think this is a bit of a weird surface. Context is usually used for multiple-RPCs-spanning properties, and users will most likely not want multiple successful calls to clobber the same variable.

**Comment by saicheems** [comment]
I see, I misunderstood, thanks for the clarification.

I think what you're suggesting is reasonable.

IIRC the interface used to look like this:
```
GetShelf(ctx context.Context, req *librarypb.GetShelfRequest, opts ...grpc.CallOption) (*librarypb.Shelf, error)
```

except `grpc.CallOption` was `option.ClientOption` - do you think it's better to only expose the `grpc` options or to wrap the call as a `ClientOption` here?
https://github.com/google/google-api-go-client/blob/master/option/option.go#L27

**Comment by pongad** [comment]
I am thinking grpc.CallOption because that's what the grpc generated code [supports natively](https://github.com/google/go-genproto/blob/master/googleapis/pubsub/v1/pubsub.pb.go#L1382).

From what I can see, it feel likes `option.ClientOption` is more geared towards option to build a client, not how to build a call. I might be reading this wrong though.

**Comment by jmuk** [comment]
+1 for additional optional parameters.

An idea is to use `gax.CallOption` here instead of `grpc.CallOption`, and add a function like `WithGrpcOption` in gax to wrap a grpc's CallOption as a gax's CallOption. This way, the call will look like
`client.GetShelf(ctx, req, gax.WithGrpcOptions(grpc.Header(header)))`.

This adds additional function call but allows customizing other gax parameters (like retry parameters) per call.

**Comment by jba** [comment]
I agree with Jun: let's use gax so we can tweak retry. (Even if retry ends
up inside gRPC, this will future-proof against new features we want to
layer on top of gRPC.)

**Comment by pongad** [comment]
SGTM, I'll work on this Monday
