### ISSUE TITLE
Ruby: Consider changing smoketest output path

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#1121]
It may be better to have ruby smoketests generate to the 'smoke_test/' path. This issue is to start a discussion to weigh the pros and cons of changing the path.

**Comment by shinfan** [comment]
FYI right now in Java we put all tests under the same path. Maybe worth considering changing the smoke test path across languages.

**Comment by landrito** [comment]
@geigerj I think your work to put the smoke tests in the acceptance test scope makes this obsolete. Closing. Reopen if I am incorrect.
