### ISSUE TITLE
[Python] remove dependency on oauth2client

### ISSUE THREAD

**Issue by jonparrott** [googleapis/toolkit#1128]

**Comment by lukesneeringer** [comment]
For documentation: @jonparrott is saying that the dependency is bogus and we do not _actually_ use it.

**Comment by lukesneeringer** [comment]
This is a P1 priority because oauth2client will be officially (externally) deprecated at the end of April.

**Comment by jonparrott** [comment]
ping on this issue

**Comment by lukesneeringer** [comment]
Have not done it yet, but I am still tracking it.

**Comment by jonparrott** [comment]
@lukesneeringer can we please do this asap? oauth2client is long deprecated and once httplib2 is gone from google-cloud-python these libraries will be pulling in completely unused dependencies.

**Comment by eoogbe** [comment]
@lukesneeringer Can you assign this P1 issue?

**Comment by eoogbe** [comment]
Via #1508
