### ISSUE TITLE
Fix Python packaging issues

### ISSUE THREAD

**Issue by jonparrott** [googleapis/toolkit#1129]
1. `setup.py`
   - [ ] use `io.open` over `open`.
   - [ ] use `Apache 2.0` instead of `apache-2.0`.
2. `setup.cfg`
   - [ ] Add [setup.cfg](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/setup.cfg) to enable wheel distribution. (We should additionally ensure packages are published as wheels).
3. `MANIFEST.in`
   - [ ] use `recursive-include google *.json *.proto` over `graft google` and `recursive-include *.json`.
   - [ ] remove unneeded `prune .tox` and `graft google`.

**Comment by eoogbe** [comment]
@lukesneeringer Can you add a priority to this?
