### ISSUE TITLE
Use better name than "service" for instance of client library

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#114]

**Comment by vchudnov-g** [comment]
Provide more context in your issues (language, what part of the code, etc.)

**Comment by pongad** [comment]
@vchudnov-g Renamed the title. The language is in the label.

**Comment by vchudnov-g** [comment]
Thanks. I saw the labels after I posted my comment. I would also have added "in the generated snippets" here and to #112 and #116. Just to make them less cryptic when we're looking back without context.
