### ISSUE TITLE
Ensure that gapic/ header version is incremented

### ISSUE THREAD

**Issue by bjwatson** [googleapis/toolkit#1162]
### What

The `gapic/` header version is currently `0.1.0` for NodeJS and PHP. We need to ensure that this increments with each new release.

### Why

If the `gapic/` version does not change, then its useless data. It would be better to report no version (i.e. `'gapic/'`) rather than a stale version.

**Comment by lukesneeringer** [comment]
This is not broken in Node; however, many GAPICs had not been regenerated since it was fixed.
