### ISSUE TITLE
Create LRO partial class for gRPC automatically

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#1210]
I suspect files like this could now be autogenerated by toolkit:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1/CloudSpeechGrpcPartial.cs

**Comment by eoogbe** [comment]
@jskeet Can you add a priority to this?

**Comment by jskeet** [comment]
This is now complete (very recently).
