### ISSUE TITLE
Consider deleting LanguageUtil

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#122]
LanguageUtil is very similar to CodegenContext.

**Comment by garrettjonesgoogle** [comment]
Note: Once all languages have been refactored to use MVVM (as of now, PHP and Java are done), LanguageUtil can be deleted (along with CodegenContext, GapicContext, and classes derived from GapicContext...)

**Comment by pongad** [comment]
@garrettjonesgoogle I'll resolve this since it will be superseded by the MVVM effort.
