### ISSUE TITLE
Ruby/Node: Generated smoke tests are broken when config uses optional parameters

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#1255]
# What
Smoke tests that are given a config that has optional parameters set causes the optional parameters to be passed in a required parameters

### Example in Logging
```rb 
logging_service_v2_client = LoggingServiceV2Client.new
formatted_log_name = LoggingServiceV2Client.log_path(project_id, "test-" + Time.new.to_i.to_s)
resource = MonitoredResource.new
labels = {}
entries = []
response = logging_service_v2_client.write_log_entries(formatted_log_name, resource, labels, entries)
```

The method call should actually look like this:
```rb
logging_service_v2_client.write_log_entries(
  formatted_log_name, 
  resource: resource, 
  labels: labels, 
  entries: entries)
```

**Comment by landrito** [comment]
cc @swcloud @geigerj

**Comment by eoogbe** [comment]
@landrito Can you add a priority to this?

**Comment by landrito** [comment]
Done.

**Comment by eoogbe** [comment]
@landrito If it's P1, can you assign it?

**Comment by landrito** [comment]
Done.

**Comment by geigerj** [comment]
@landrito What's the status of this issue?

**Comment by landrito** [comment]
Haven't gotten around to this issue.

**Comment by geigerj** [comment]
@eoogbe, could you PTAL?

**Comment by landrito** [comment]
cc @lukesneeringer This is a problem with nodejs as well as seen in this CI build error. https://circleci.com/gh/googleapis/nodejs-logging/162?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
