### ISSUE TITLE
clientconfig generates json files at toplevel

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#126]
When I built a gapic client for logging/v2 API, I've noticed that the generated place for clientconfig is different from the code location. client config json files are always generated at the toplevel directory, while py files are in google/logging/v2 (rb files are lib/google/logging/v2).

But our generated code expects the JSON files in the directory where the code files reside.

This means client-config target directory has to be injected by some language-specific parameters -- I don't have concrete ideas to achieve this.

**Comment by jmuk** [comment]
@geigerj @garrettjonesgoogle

**Comment by geigerj** [comment]
The toolkit currently drops the client config at the top level without trying to read in any configuration (see [here](https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/clientconfig/ClientConfigGapicProvider.java#L60)).

Where do the JSON client config-using languages expect the file to be located? If it can be derived from the [package name](https://github.com/googleapis/toolkit/blob/master/src/main/proto/com/google/api/codegen/config.proto#L107), that would be an easy fix. Otherwise, let's add a field to `LanguageSettingsProto` in `config.proto` to specify the client config path.

**Comment by geigerj** [comment]
It looks like PHP expects the config to be located [under a directory called "resources"](https://github.com/googleapis/toolkit/blob/90116fd563f9fe9080dbae2066770e64e5f62f5a/src/test/java/com/google/api/codegen/testdata/php_library.baseline#L218). Therefore, let's make the location optionally configurable in the GAPIC yaml. The code generator call fall back to using the package name if the JSON location is unspecified.

**Comment by geigerj** [comment]
Actually, I'm now realizing that there is language-specific logic in converting a package name to a directory structure, so it's not possible to fall back to package name in a language-independent way by default.

At the same time, specifying the full path to the client config in the GAPIC yaml would have a lot of redundancy with the package name.

@jmuk @garrettjonesgoogle thoughts?

**Comment by garrettjonesgoogle** [comment]
We could treat this the same way we treat the paths for the api wrapper classes - each language might or might not base it on the package name, and has a way of translating the package name to the path that it wants. So, maybe each language needs a context function to provide the right path.

**Comment by geigerj** [comment]
To clarify, are you suggesting that each language would use a different provider for running the JSON client config? Right now, there's only a single, language-independent context for the client config.

**Comment by garrettjonesgoogle** [comment]
I was kind of suggesting that, but that is a mistake. We just need this particular value parameterized per language somehow, but using code that transforms the existing package config value we have already into the right path for the client config for the language.

**Comment by geigerj** [comment]
OK, that seems possible. We can

- Remove `getFilename()` from the JSON config snippets interface
- Make `ClientConfigGapicProvider` abstract, with `output()` depending on the abstract method `String getFilename(String packageName)`. Each language can have a provider that extends `ClientConfigGapicProvider` and implements this method.

**Comment by garrettjonesgoogle** [comment]
I'd prefer to use the Strategy pattern over the Template Method pattern, it makes the code a lot more modular.
