### ISSUE TITLE
remove timeout from constructor parameter

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#127]
I am wondering why 'timeout' is a separate parameter for the constructor (in Python and Ruby).

It's defined in the client-config, and the parameter can be configurable by #70, possibly we can simply remove 'timeout' parameter, the 'default_timeout' constant, and some other related code?

**Comment by jmuk** [comment]
@geigerj @tbetbetbe, thoughts?

**Comment by garrettjonesgoogle** [comment]
Adding @chrisdunelm too, for him to follow timeout-related conversations

**Comment by geigerj** [comment]
I don't think timeout is actually defined in the client config, but perhaps it should be.

**Comment by geigerj** [comment]
I would propose:

- Add per-method timeout configuration to the GAPIC config, and propagate to the JSON client config
- Remove the `timeout` parameter and `default_timeout` constant from the generated API objects
