### ISSUE TITLE
Streaming C# samples create task without awaiting it

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#1271]
This generates a CS4014 warning. [Sample code](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/06746f648a8aefa08fe7b847971801e801242bc8/apis/Google.Cloud.Speech.V1/Google.Cloud.Speech.V1.Snippets/SpeechClientSnippets.g.cs#L306)

**Comment by eoogbe** [comment]
@jskeet Can you add a priority to this?
