### ISSUE TITLE
Add protobuf type coercion of native Array/Hash to GAPIC.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/toolkit#1273]
/cc @remi for tracking

One usability concern for using our autogenerated libraries in Ruby is that having to import protobuf message types and instantiate them manually can be a real pain in the neck, especially for APIs (like Vision) with deeply nested protobuf messages.

In Python and Node, it is possible to send native types (dicts or objects, respectively) that conform to the appropriate structure, and these are coerced to the appropriate protobuf messages automatically. Sadly, this does not work in Ruby, and you get an exception if you try.

I would like GAPIC to smooth this over somewhat for our users. Since toolkit always knows what type is expected, I would like for the GAPIC methods to attempt to coerce the type.

Basically this entails checking to see if the user sent a Hash (for protobuf messages) or Array (for repeated fields), and if they did, call the protobuf message type's constructor and send the native structure. A user that sent invalid data will get a useful exception at this spot (which is great).

### Scope of Work

  * [x] Update toolkit to look for `Hash` objects when messages are expected, and coerce.
  * [x] Update toolkit to look for `Array` objects when repeated fields are expected, and coerce.
  * [x] Ensure that deeply nested structures still work, and coerce recursively. (This may "just work".)
  * [ ] ~P2~ P1: Update samplegen to use native objects in canonical samples. (It is in bounds to close this issue with this item not done as long as a new one is made to track.)

**Comment by landrito** [comment]
I did some research. Looks like the native protobuf initialization does not "just work" 😞. Submessage fields must either be nil or of the submessage type as seen [here](https://github.com/google/protobuf/blob/master/ruby/ext/google/protobuf_c/storage.c#L192). That being said, we'll have to do the coercion ourselves. 

I wrote up a quick example of how we can do that: https://gist.github.com/landrito/fefcbc6739dc89748cff14e69311586d

**Comment by landrito** [comment]
Also, I think the samplegen update is P0. With the samplegen update, we'll be able to rely on generated unit tests to verify the coercion is working.

**Comment by lukesneeringer** [comment]
> Also, I think the samplegen update is P0. With the samplegen update, we'll be able to rely on generated unit tests to verify the coercion is working.

That is fair. :-)

**Comment by geigerj** [comment]
I am going to close this issue, since Hash coercion has already been implemented.
