### ISSUE TITLE
Ruby array (and hash?) type documentation should specify element type

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1311]
### What

We document that input types are arrays but don't specify what type the arrays contain. (We should similarly confirm that we document the parameterized types for inputs that come from proto `map` types.)

### Context

https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1476

**Comment by geigerj** [comment]
@eoogbe is there any update on this issue?

**Comment by eoogbe** [comment]
Toolkit is documenting appropriately. (Compare [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/google-cloud-monitoring/v0.24.0/google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb#L617) and [here](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=create_time_series-instance).) This appears to be a problem with the documentation parser.
