### ISSUE TITLE
Allow passing path to keyfile to use for credentials

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1324]
### What

We don't want to force users to read gRPC docs and construct a `Grpc::ChannelCredentials` in the common situation that they want to use a keyfile.

### How

Allow the `initialize` method of the client object to accept either a `string` representing the path to a keyfile, or a `Grpc::ChannelCredentials` as the value to `chan_creds`. If a `string` is received, GAX should construct the `Grpc::ChannelCredentials` automatically.

cc: @landrito @eoogbe

**Comment by blowmage** [comment]
Can the object also be an IO object, so users can pass a File object instead of the file's path?

**Comment by geigerj** [comment]
@blowmage Sure, that makes sense.

**Comment by sundewei** [comment]
Hi,
Sorry to jump in but we are in need of evaluating GCP Monitoring quickly.
May I know if you have an ETA of this case?
Thanks.
Dewei

**Comment by landrito** [comment]
I'll get started on it soon! I am thinking I can get it merged by end of week.

**Comment by geigerj** [comment]
Hi @sundewei. Our ETA for this change is July 1. In the meantime, it should be already be possible to construct a `Grpc::ChannelCredentials` from a keyfile, although it's more verbose than what we're proposing here.

**Comment by sundewei** [comment]
Hi Geigerj,
Would you mind providing me with an example?
Here is my code:
`CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(
            ServiceAccountCredentials.fromStream(new FileInputStream(gcpJsonKeyFilePath)));

final MetricServiceClient client = MetricServiceClient.create((MetricServiceSettings)MetricServiceSettings.newBuilder().setCredentialsProvider(credentialsProvider).build());`

I am getting this error `Exception in thread "main" java.lang.IllegalStateException: Missing required properties: totalTimeout initialRetryDelay retryDelayMultiplier maxRetryDelay initialRpcTimeout rpcTimeoutMultiplier maxRpcTimeout`

Many thanks.

Dewei

**Comment by geigerj** [comment]
@sundewei Ah, sorry. This issue is tracking a change for the Ruby client library, not Java. Can you re-file this under https://github.com/GoogleCloudPlatform/google-cloud-java/issues/new and tag @garrettjonesgoogle? He should be able to help you over there.

**Comment by sundewei** [comment]
Thanks a lot for the pointer, I have created a new ticket for it.

Dewei

**Comment by geigerj** [comment]
@landrito This can be closed, right?

**Comment by landrito** [comment]
Correct.
