### ISSUE TITLE
Incorrect node.js path mapping for alpha/beta versions

### ISSUE THREAD

**Issue by tigersoldier** [googleapis/toolkit#1335]
https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/nodejs/NodeJSCodePathMapper.java#L30

There shouldn't be any number required after alpha/beta. The regex doesn't match version names like v1alpha.

**Comment by geigerj** [comment]
@swcloud @lukesneeringer

**Comment by geigerj** [comment]
Hi @tigersoldier, this tool is currently written with certain Google API conventions assumed. Under those conventions, alpha/beta releases are followed by a number. (Please feel free to re-open if that doesn't address your concern.)

**Comment by geigerj** [comment]
I was mistaken; the tooling framework is more permissive here. See https://github.com/googleapis/api-compiler/blob/master/src/main/java/com/google/api/tools/framework/aspects/versioning/model/ApiVersionUtil.java#L40

**Comment by eoogbe** [comment]
@geigerj Can you add a priority to this?

**Comment by eoogbe** [comment]
Fixed #1545
