### ISSUE TITLE
Provide the ability to set a namespaced variable as a default argument.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/toolkit#1336]
In NL, we want to set a sensible default for `encoding`. However, the value is different per-environment and per-language.

For example, in Python, the correct value properly defined as:

```python
lambda: 'utf-16' if sys.maxunicode < 65536 else 'utf-32'
```

For Node, the correct value is always `utf-16`.

And so on and so forth.

I would like these to be values defined in `google.gax`, and set the toolkit default to something like `google.gax.utils.ENCODING`. This entails that the variable can be a function default, _and_ that toolkit properly adds the appropriate import.

- [ ] C#
- [ ] Go
- [ ] Java
- [ ] Node.js
- [ ] PHP
- [ ] Python
- [ ] Ruby

**Comment by geigerj** [comment]
Per offline discussion with @lukesneeringer, we are going to shelve this proposal. A key problem is that the constant value, like `ENCODING`, may be present in a nested message within the request, and there's no easy way to set _and_ document the default value with our current generator set-up; this limits the applicability of this code generator feature. Getting this right in the code generator is likely to be expensive and complex.

In all cases, this should be relatively simple/low cost to implement in the manual component of the partial GAPIC. We might even be able to implement this in the manual code such that when the GAPIC is updated with a new method, the default value automatically applies to the new GAPIC method without changes to the manual code.
