### ISSUE TITLE
Ruby: Provide a friendly workflow for enums

### ISSUE THREAD

**Issue by frankyn** [googleapis/toolkit#1337]
Hi,

I have the following snippet for the Video Intelligence API below and I'm trying to improve the developer experience. Using the enum `Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION` could be better if the namespace was consistent with the namespace used for the `VideoIntelligenceServiceClient` class **OR** using symbols such as `:LABEL_DETECTION`.

I'm open to interpretation, and I believe one of these options will help improve the developer experience.

Thank you. 

```ruby
  require "google/cloud/video_intelligence/v1beta1"

  video_client = Google::Cloud::VideoIntelligence::V1beta1::VideoIntelligenceServiceClient.new
  features     = [Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION]

  # Register a callback during the method call
  operation = video_client.annotate_video path, features do |operation|
    raise operation.results.message? if operation.error?
    puts "Video labels completed"

    annotation_results = operation.results.annotation_results

    if annotation_results.any?
      annotation_results.each do |annotation_result|
        puts "Labels:"
        annotation_result.label_annotations.each do |label_annotation|
          puts "\tDescription: #{label_annotation.description}"
          label_annotation.locations.each do |location|
            if location.level == :VIDEO_LEVEL
              puts "\tLocation: Entire video"
            else
              segment      = location.segment
              start_offset = segment.start_time_offset / 1000000.0
              end_offset   = segment.end_time_offset / 1000000.0
              puts "\tLocation: #{start_offset}s - #{end_offset}s"
            end
          end
        end
      end
    else
      puts "No labels detected in #{path}"
    end
  end

  puts "Waiting for operation to complete..."
  operation.wait_until_done!
```

**Comment by frankyn** [comment]
After speaking with @remi, she prefers option 2:

Use symbols such as `:LABEL_DETECTION` instead of`Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION` because it's idiomatic in Ruby. Similar to `:VIDEO_LEVEL` shown in the previous comment.

**Comment by geigerj** [comment]
> using symbols such as :LABEL_DETECTION

From experience with Python, the enums require namespacing, since we have examples of APIs that have different enums of the same name under different namespacing.

For Python we alias the enums under the same namespace as the client, e.g., https://github.com/googleapis/toolkit/blob/b4df82d87f0ebfa57f9c5b510be8dd6f37f45194/src/test/java/com/google/api/codegen/testdata/python_doc_enum_library.baseline

If we want to support option 2 (symbols), we can probably disambiguate the symbols in GAX using the type signature of the method, but that's a little more complicated.

@landrito How long do you think this change would take for each option?

**Comment by frankyn** [comment]
Follow-up to disambiguate the symbols. I was thinking the method could map the symbol to available enums such as:

```ruby
enum_values = {LABEL_DETECTION: Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION}
features = [:LABEL_DETECTION]
mapped_features = features.map do |feature|
  enum_values[feature]
end
```

Not sure how difficult it would be to implement though. Thanks for feedback!

**Comment by geigerj** [comment]
@frankyn The concern is more that a particular API might have two enums with the same name, so you can't construct the `enum_values` map you're showing. For example, bigtable defines two different STATE_NOT_KNOWN enums in [instance.proto](https://github.com/googleapis/googleapis/blob/5fc7a79958827d505671a14c1343087a45b567e6/google/bigtable/admin/v2/instance.proto#L36). This is not uncommon.

We can still figure out which `STATE_NOT_KNOWN` type is needed for the method given the method's signature in the proto file, but it requires slightly more work.

**Comment by frankyn** [comment]
Ah, IIUC symbols would introduce a pigeonhole problem if generalized over all methods. So it would depend on the signature of the method. I updated my previous comment to have an example of what the generated output may look like. Is this what you were thinking?

**Comment by frankyn** [comment]
(ping @landrito) do you have an estimate for long this could take?

**Comment by landrito** [comment]
I think that the disambiguation of the labels can happen at the protobuf level.

ie This should 'just work'
```rb
instance = Instance.new({
  state: :STATE_NOT_KNOWN
})

cluster = Cluster.new({
  state: :STATE_NOT_KNOWN
})
```

That being said I make a PR to have the samples updated to use labels in today and probably have it merged by wednesday at the latest.

**Comment by landrito** [comment]
Actually! I just remembered that I made it such that the samples worked this way in https://github.com/googleapis/toolkit/pull/1253.

As seen in this file: https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/ruby_doc_main_library.baseline#L914

It also is being tested in generated tests
https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/ruby_test_library.baseline#L881

That being said, you should be able to use labels for enums in your samples.

**Comment by frankyn** [comment]
Ah, thanks @landrito! I just tried it and it worked.
