### ISSUE TITLE
node.js: comments are not escaped properly

### ISSUE THREAD

**Issue by tigersoldier** [googleapis/toolkit#1344]
It's common for one platform APIs to have proto documentation for resource path patterns that contains `*/`. For example `/libraraies/*/books/*/`. The generated node.js code simply put that into the jsdoc without escaping, causing `*/` ending the jsdoc incorrectly.

**Comment by lukesneeringer** [comment]
Do JavaScript block comments even _have_ escaping?

**Comment by lukesneeringer** [comment]
I just checked the documentation and can not tell (although obviously something mangled-looking is better than a syntax error, so we should definitely do this.)

**Comment by eoogbe** [comment]
Duplicate #615
