### ISSUE TITLE
Remove over-long match_* methods

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1374]
### What

Several weeks ago, we decided to remove the Ruby path template match_* methods. This was because they had overly long names (sometimes violating line length limits), non-idiomatic, and (to our knowledge) unused. We should do this before we start declaring beta on GAPIC-only packages.

### How

Remove this section from the template

**Comment by geigerj** [comment]
@landrito Do you think you fit this in this week?

**Comment by landrito** [comment]
Yep shouldn't take too long.
