### ISSUE TITLE
Figure out code gen version

### ISSUE THREAD

**Issue by swcloud** [googleapis/toolkit#1393]
In src/main/resources/com/google/api/codegen/nodejs/main.snip

  var CODE_GEN_NAME_VERSION = 'gapic/{@xapi.packageVersion}';

The version here should be @xapi.toolkitVersion.

**Comment by eoogbe** [comment]
@landrito Can you add a priority to this?

**Comment by landrito** [comment]
This has been fixed.

**Comment by landrito** [comment]
Oh sorry, this is incorrect.

**Comment by landrito** [comment]
Closing, this has been refactored out.
