### ISSUE TITLE
Add "Enable billing for your project" step in auto-gen README

### ISSUE THREAD

**Issue by omaray** [googleapis/toolkit#1407]
Looking at the [README for Monitoring in Ruby](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-monitoring), we notice that the second step, which is to enable billing, is missing. The following text and link should be shown as step 2:

2. [Enable billing for your project](https://support.google.com/cloud/answer/6293499#enable-billing)

**Comment by eoogbe** [comment]
@landrito Can you add a priority to this?

**Comment by eoogbe** [comment]
@landrito Are you still working on this? I can take over if not.
