### ISSUE TITLE
Drop oracle jdk7 from CI?

### ISSUE THREAD

**Issue by bootstraponline** [googleapis/toolkit#1424]
> oraclejdk7 is unfortunately no longer available in Trusty after our latest updates, since we can no longer support oraclejdk7 on our recent build images due to Oracle's withdrawal. See: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html
>
> https://github.com/travis-ci/travis-ci/issues/7019#issuecomment-316769716

It seems like we should drop oraclejdk7. Is there any issue with requiring JDK 8 and above?

**Comment by garrettjonesgoogle** [comment]
Yeah, looks like we should drop oraclejdk7, but I think we want to retain openjdk7 for now.

**Comment by bootstraponline** [comment]
openjdk7 is broken on trusty. looks like we are stuck on the legacy Ubuntu for now. 😭 

- https://github.com/docker-library/openjdk/issues/117
- https://travis-ci.org/googleapis/toolkit/jobs/255774665 `no such provider: SunEC`

**Comment by eoogbe** [comment]
Fixed
