### ISSUE TITLE
Generated Python libraries should use google.cloud.future.operation instead of google.gax._OperationFuture

### ISSUE THREAD

**Issue by jonparrott** [googleapis/toolkit#1426]
`google.cloud.future.operation` is in `google-cloud-core`.

**Comment by geigerj** [comment]
This is similar to the discussion we've been having elsewhere about `core` and `gax`, but we should not be introducing dependencies on `google.cloud` packages in generated Python libraries, which might not be for cloud APIs.

**Comment by jonparrott** [comment]
How do we feel about introducing it in the interim until core/gax converge?

**Comment by geigerj** [comment]
I have no objection to that as long there's plan to change the dependency namespace in a way that'll be transparent to users.

FYI @ethanbao, who's working with our non-cloud APIs.

**Comment by jonparrott** [comment]
yep, that's the idea as mentioned in the internal doc about the convergence (under 'Concern over the name google.cloud.core')

**Comment by eoogbe** [comment]
This appears to be done
