### ISSUE TITLE
Reform Ruby's doc-gen code

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#143]
From internal-feedback: someone could be confused by the .rb files for documenting the message structures, because they are rb files and could be scared how they conflict with existing files.

That wasn't my intention, and actually they (the generated code) don't cause problems, that's harmless. However, more experienced in Ruby the user is, the more confusing this code structure is.

An idea is to generate markdown documents for those messages instead of rb files, and make links to those markdown messages, so the users clearly see those files are purely for documentation and no use as actual Ruby code.

**Comment by jmuk** [comment]
cc: @tbetbetbe

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
