### ISSUE TITLE
PHP template causes cryptic exception when no service doc is present

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/toolkit#1433]
I have a proto with no doc comment for the service it describes. When I try to generate the PHP GAPIC, I get:
```
Unexpected exception:
      com.google.api.tools.framework.snippet.SnippetSet$EvalException: snippet evaluation error: php/main.snip:45: exception when invoking method 'firstLine': java.lang.IndexOutOfBoundsException: index (0) must be less than size (0).
        at com.google.api.tools.framework.snippet.Elem$Reflect.tryEvalAsMethod(Elem.java:241)
        at com.google.api.tools.framework.snippet.Elem$Reflect.eval(Elem.java:205)
```
If I add a dummy comment to the service, the generation succeeds.

I think we should either generate code even with a missing service doc (like the other languages do), or explicitly check and have an informative error message rather than this exception.

**Comment by pongad** [comment]
Related: #1411 . I'm not completely sure how to address the comments in the review though :(
