### ISSUE TITLE
Stutter in generated comments

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/toolkit#1439]
In some proto files, the comments in the service declaration already begin with the service or method name (in a way reminiscent of Go style).  The generated Go GAPIC seems to assume that  the comments start with verbs, so it always prepends the identifier name. This results in stutter for these cases. For example, the proto
```
 // Create is used to ....
rpc Create(...)...
```
results in Go code
```
// Create create is used to ...
func (c *Client) Create(...)...
```

I suggest that instead we implement something along the lines of the following pseudo-code:
```
if lower(proto.comment.word[0])==lower(method.name) {
   gapic.comment = method.name + proto.comment.word[1:]
}
```

Do other languages have a similar issue?

**Comment by pongad** [comment]
The API style guide mandates that the documentation should start with a verb though. I'm OK with fixing this, but I think it's better to either ask API team to fix doc or just fix it for them. WDYT?

**Comment by vchudnov-g** [comment]
In this case, it was an external API that exhibited this situation. I suppose we have the option of being opinionated and assuming everyone uses this particular style convention, or being able to somewhat easily accommodate another reasonable (and common?) style pattern.

(And I say this pattern is reasonable because it's what Go uses, after all :-) )

**Comment by pongad** [comment]
Ah I see. I didn't realize this was from external API. I'll fix it during the fixit week.
