### ISSUE TITLE
Incorrect googleapis-common-protos dependency in Ruby gemspec

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1440]
### What

The Ruby gemspec currently specifies a dependency on `google-common-protos` (which does not exist). In fact, the dependency should be on `googleapis-common-protos`.

**Comment by geigerj** [comment]
cc: @landrito

**Comment by landrito** [comment]
This is resolved in googleapis here https://github.com/googleapis/googleapis/blob/master/gapic/packaging/dependencies.yaml#L84

#1442 should be able to resolve this for the test cases in toolkit.

**Comment by geigerj** [comment]
Thanks, Ernest. This must be a problem with my local environment.
