### ISSUE TITLE
Ruby client files need to `require 'pathname'`

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1441]
### What

Recent changes introduced a dependency on `Pathname`, which the generated code does not require. This leads to failures like:

```
$ irb
2.2.6 :001 > require 'google/cloud/logging'
NameError: uninitialized constant Google::Cloud::Logging::Pathname
```

**Comment by geigerj** [comment]
cc: @landrito

**Comment by landrito** [comment]
😭 I found the problem. I use [`pry`](https://github.com/pry/pry) a different repl than irb. Apparently it implicitly requires `pathname` at the global scope which made it such that this error never appeared for me in my tests. 

I guess I have go back to using irb.
