### ISSUE TITLE
Move test source files from testdata to testsrc folder

### ISSUE THREAD

**Issue by eoogbe** [googleapis/toolkit#1495]
The testdata folder is getting unwieldy and currently houses two concerns:
- test source files - input for tests
- test data files - baseline output for tests

These concerns should be in their own directories, both for better organization and to ease comprehension of the test input and output files.

cc/ @shinfan @garrettjonesgoogle

**Comment by geigerj** [comment]
@eoogbe A step further, would it make sense to have subdirectories per-lang in `testdata`? There are an enough baseline files now to be unwieldy to sort through manually.

**Comment by eoogbe** [comment]
@geigerj That's a good idea. PR forthcoming.
