### ISSUE TITLE
Config gen: "spi" in Java package

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1501]
### What

The Java configgen produces a "spi" in the package path. @shinfan can you confirm whether this should be generated, and remove it if it shouldn't be?

https://github.com/googleapis/toolkit/blob/605c05d02897d0a1f3e1b0cf4949df52ed63d746/src/main/java/com/google/api/codegen/configgen/transformer/LanguageTransformer.java#L39

### Why

No packages configured in https://github.com/googleapis/googleapis use a package name of this form.

**Comment by garrettjonesgoogle** [comment]
This should be removed.
