### ISSUE TITLE
Is PUBLISHING.rst still correct?

### ISSUE THREAD

**Issue by eoogbe** [googleapis/toolkit#1527]
The PUBLISHING.rst for the generated Python code references tox, but I believe we removed tox. Are we still using it for publishing docs?
/cc @lukesneeringer

**Comment by lukesneeringer** [comment]
It is almost definitely wrong.

**Comment by eoogbe** [comment]
Should we get rid of it or update it to be correct?

**Comment by lukesneeringer** [comment]
Scrap it. We have an overall one in google-cloud-python.
