### ISSUE TITLE
Allow Google::Cloud::Credentials to be passed to GAPIC

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1569]
### What

GAPIC classes that take a credentials class should be able to be used with instances of `Google::Cloud::Credentials` when they are used to implement manually written client libraries.

This means loosening a type check (see, for example, https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1727/commits/c439522aec458db7f0853daae9631c1a9584031b).

It also means that we probably should be able to configure the path to the credentials class when multiple services of a single product should share the same credentials. (See, for example, https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1727/commits/c3f9408f7a3e9e62fe0bfce9c93841d0a61c980f). Alternatively, we could continue to generate multiple credentials classes and make it the responsibility of the manual layer to overwrite and set the right one by default.

@landrito curious about your thoughts on the second part, since that is potentially trickier.

**Comment by landrito** [comment]
Hm. Doing this will cause an added dependency on google-cloud-core. Are you okay with adding that dependency?

**Comment by geigerj** [comment]
Good point. It is better to make `Google::Cloud::Credentials` subclass `Google::Gax::Credentials` for the first problem. We'd still need to configure the path for the second problem.

**Comment by eoogbe** [comment]
@geigerj Can you add a priority?

**Comment by geigerj** [comment]
This is obsolete. Both `Google::Cloud::Credentials` and `Google::Gax::Credentials` have been deprecated in favor of `Google::Auth::Credentials`, which is now supported.
