### ISSUE TITLE
Ruby: smoke test/README sample does not handle keyword args

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1590]
### What

The Ruby smoke test/README sample treats all arguments as required, even when they are in fact keyword arguments. This results in the sample/system test failing with syntax errors.

### Example

See the hand-edits necessary here:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1750/commits/23f468b85bb0bfac1ffd4a6e955a6bdbcc2ddd8e

/cc @landrito

**Comment by eoogbe** [comment]
Duplicate #1255
