### ISSUE TITLE
[nodejs]: client instantiation isn't correct

### ISSUE THREAD

**Issue by jmdobry** [googleapis/toolkit#1599]
Related to #1598 

The problem is in [src/v1beta1/firestore_client.js#L409](https://github.com/googleapis/nodejs-firestore/blob/master/src/v1beta1/firestore_client.js#L409) and appears in a bunch of other places in the file:

```diff
- * var firestore = require('firestore.v1beta1');
- *
- * var client = firestore.v1beta1({
- *   // optional auth parameters.
- * });
+ * var Firestore = require('@google-cloud/firestore');
+ *
+ * var client = Firestore
+ *   .v1beta1({
+ *     // optional auth parameters.
+ *   })
+ *   .firestoreClient({
+ *     // other optional parameters
+ *   });
```

**Comment by landrito** [comment]
I don't think this is actually a problem general to all generated clients but to how firestore made manual edits to the client. This example shows how to use the generated `src/index.js` to get the v1beta1 client. 

This line:
https://github.com/googleapis/nodejs-firestore/blob/master/src/index.js#L1124
for generated clients is actually a function that initializes the firestore client.

**Comment by jmdobry** [comment]
Invoking the `v1beta` function returns an instance of `FirestoreClientBuilder`, on which you then need to call `FirestoreClientBuilder#firestoreClient()`. [Here it is in action](https://github.com/googleapis/nodejs-firestore/blob/master/src/index.js#L235).

**Comment by landrito** [comment]
Agreed, but that is firestore specific since it is not using the generated v1beta1 export. What would be generated would look like this: https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/nodejs/nodejs_version_index_library.baseline#L94.

**Comment by jmdobry** [comment]
So what's our action?

**Comment by landrito** [comment]
@lukesneeringer Should we switch firestore `src/index.js`'s v1beta1 module export to be the generated one?

**Comment by lukesneeringer** [comment]
I am discussing this with @landrito in chat right now (sorry, I had an emergency dental appointment followed by having to go to the airport). I think it is fine for the `.v1`, `.v1beta1`, etc. exports to be the generated client always. That is what we have been doing for a long time, and it is the only way to keep the auto-generated samples sane.

**Comment by landrito** [comment]
Moving this issue over to https://github.com/googleapis/nodejs-firestore

**Comment by lukesneeringer** [comment]
I think I may not have understood this issue. In particular, @jmdobry points out that a solution that does the double-invocation for you will not work well for APIs with more than one service client.

**Comment by lukesneeringer** [comment]
#1406 ends up addressing this.
