### ISSUE TITLE
all: drop path templates, replace with string concatenation

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#1639]
**Note**: don't escape input strings.

Want to go from
```
def foo(project, bar):
    return _FOO_TEMPLATE.render({'project': project, 'bar': bar})
```

to
```
def foo(project, bar):
    return 'projects/{0}/bars/{1}'.format(project, bar)
```

- [x] C#
- [x] Go
- [ ] Java
- [x] Node.js
- [ ] PHP
- [x] Python
- [ ] Ruby

**Comment by jskeet** [comment]
C# has never done this. From [PathTemplate.cs](https://github.com/googleapis/gax-dotnet/blob/master/src/Google.Api.Gax/PathTemplate.cs)

> This class performs no URL escaping or unescaping. It is designed for use within GRPC, where no
URL encoding is required.

(We do validation and some other work, so the PathTemplate class still has value, but we don't do URL escaping.)

**Comment by lukesneeringer** [comment]
For languages not exposing this on a GA surface yet, should we just remove them entirely? At least in dynamic languages, they seem less intuitive to me than "bring your own string substitution".

I assume they are more valuable in C# and Java where more full-featured IDEs cause them to provide more value.

In Python and Node, I feel like they just clutter the method list in the docs and make it harder to spot the stuff you really want. :-)

**Comment by lukesneeringer** [comment]
Counter-argument: Removing them arguably causes unnecessary customer churn.

**Comment by jskeet** [comment]
For C# they very significantly improve usability, so I don't think we need to remove them there. I would imagine Java is the same.

**Comment by lukesneeringer** [comment]
@jskeet Curious question: Is the usability improvement more or less tethered to "the IDE does nice auto-completion-y things for you?" Or does it offer benefits even outside of that?

My intuition above was, "I bet they are valuable in C# and Java because the ecosystem derives more benefit from them there." But if you think they offer a separate usability improvement that I am missing, I would want to understand that. :-)

**Comment by lukesneeringer** [comment]
Regardless on where we end up on my grenade toss, [Python's new implementation does no url-escaping](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/api_core/google/api_core/path_template.py).

**Comment by lukesneeringer** [comment]
As best as I can tell, [Node does not either](https://github.com/googleapis/gax-nodejs/blob/master/lib/path_template.js), although [this thing](https://github.com/googleapis/gax-nodejs/blob/master/lib/path_template_parser.js) defies comprehension at 6:30 AM, so it is a bit hard to be sure.

If there is any URL encoding in Node, it is not using `encodeURI` or `encodeURIComponent`, which is the built-in function in JavaScript to do that. So we should be safe as long as we did not roll our own URL encoding function for this.

**Comment by jskeet** [comment]
@lukesneeringer: Not so much auto-completion as "It's absolutely clear what value I should pass in - and the compiler will even prevent me from passing in the wrong kind of resource name."

We saw in UX testing that developers would get stuck not knowing what string to pass into methods (even if they'd previously deleted sample code that did that) whereas when they have something like `TopicName`, they can use `new TopicName` - at which point autocompletion *is* important.

The difference in before and after UX testing sessions was pretty clear, IIRC.

**Comment by garrettjonesgoogle** [comment]
It should be noted that with generated classes like `TopicName`, the user still doesn't interact with `PathTemplate`, which is just an implementation detail at that point.

**Comment by lukesneeringer** [comment]
@jskeet Thanks, that sounds convincing.

**Comment by saicheems** [comment]
Looks like the decision is to do nothing more, for now.
