### ISSUE TITLE
Packaging: Auto-generated modules are missing a `setup.cfg`

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/toolkit#1676]
_From @dhermes on November 1, 2017 18:50_

Was [#4307](https://github.com/GoogleCloudPlatform/issues/4307).

_Copied from original issue: GoogleCloudPlatform/google-cloud-python#4314_

**Comment by dhermes** [comment]
I'd expect the content to simply be:

```
[bdist_wheel]
universal = 1
```

This way wheels will be universal (and not just for the given Python version that compiled them).

**Comment by eoogbe** [comment]
This appears to be fixed
