### ISSUE TITLE
PHP: sample_code_init_fields not used for optional arguments

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#1706]
See for example in [this PR](https://github.com/googleapis/api-client-staging/pull/467/files#diff-02204bf51b0fe557a422ca5967d33136R488), the parameter was made optional, and the init fields are excluded from the sample.

cc @ethanbao If other languages are found to be affected, we can expand the scope of this issue

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority?

**Comment by michaelbausor** [comment]
Fixed in #1775
