### ISSUE TITLE
Python: Fix python namespace init files.

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#1708]
### What
I had originally thought that the logic for python namespace files had to do with the position the of the namespace in relation to the full package path.

### Short term fix
Change the logic to simply make `google` and `google.cloud` namespace packages.

### Long term fix
Design a way for the user to specify which packages are namespace packages.

**Comment by eoogbe** [comment]
Related #881

**Comment by lukesneeringer** [comment]
Also: `namespace_packages` in `setup.py` needs to match.
