### ISSUE TITLE
Ruby: Toolkit snake cases gRPC stub methods incorrectly

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#1760]
### What

The gRPC stub translates CamelCased proto method names differently from toolkit when the method contains multiple capitalized letters in a row, resulting in a runtime error when the Ruby service object is initialized.

### Context

Container contains the method [`StartIPRotation`](
https://github.com/googleapis/googleapis/blob/e94093478ca3860066b254663abf0704de484cbd/google/container/v1/cluster_service.proto#L182). The generated gRPC stub then contains a method `start_ip_rotation`, but the GAPIC attempts to reference the method `start_i_p_rotation`. Note the spurious underscore between in `i_p` in the GAPIC.

cc: @landrito

**Comment by landrito** [comment]
Did some digging. It seems the exact logic that controls the camel to snake casing is here: https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/service.rb#L33

**Comment by geigerj** [comment]
@landrito Wow, great find! Thanks for digging into this!
