### ISSUE TITLE
Discogapic: support setX(String) / (String)getX methods when X is a resource name type

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/toolkit#1804]

**Comment by garrettjonesgoogle** [comment]
Note: after https://github.com/googleapis/toolkit/pull/1803 is submitted, discogapic samples will be broken until this change is made.

**Comment by andreamlin** [comment]
@garrettjonesgoogle If there's an Address message type with an address entity `projects/{project}/regions/{region}/addresses/{address}`, should the generated Address message class have getters and setters for project, region, and address; or should Address only have methods to interact with a formatted AddressName?

**Comment by garrettjonesgoogle** [comment]
It is unfortunately neither: there should jus be methods to interact with the String form of the address name. The generated sample code should direct people to the AddressName class to help them with parsing/formatting.

**Comment by andreamlin** [comment]
Done.

**Comment by andreamlin** [comment]
Done when https://github.com/googleapis/gax-java/pull/481 gets merged in.
