### ISSUE TITLE
Field comments - only use first sentence.

### ISSUE THREAD

**Issue by broady** [googleapis/toolkit#184]
```
    // REQUIRED: The resource for which policy is being specified. `resource` is usually specified as a path, such as, `projects/{project}/zones/{zone}/disks/{disk}`. The format for the path specified in this value is resource specific and is specified in the documentation for the respective SetIamPolicy rpc.
```

should just be

```
    // REQUIRED: The resource for which policy is being specified.
```

**Comment by garrettjonesgoogle** [comment]
Why?

**Comment by broady** [comment]
They're extremely long. Wrapping the comment is a good alternative.

The primary case for these generated samples is embedding in docs - we want to stick to ~ 100 chars so they display nicely in the docs.

**Comment by broady** [comment]
cc @pongad

**Comment by garrettjonesgoogle** [comment]
The original content (from the proto) is already wrapped to a reasonable line length; is the Go codegen unwrapping it?

**Comment by broady** [comment]
It appears to be. Check out the baseline: 
https://github.com/googleapis/toolkit/blob/d3690b1125eda3b728157caac32c812c65b2a160/src/test/java/com/google/api/codegen/testdata/discoveries/go/go_cloudresourcemanager.v1beta1.json.baseline

**Comment by pongad** [comment]
I think the primary confusion here is that in VKit, the comments are already reasonably line-wrapped but descriptions in Discovery docs are not.
I'll add Discovery label to this.

@broady Do you think it is reasonable to just line-wrap the comment? My primary concern is that some random Discovery doc might have unhelpful first sentences.

**Comment by pongad** [comment]
@broady Do you think #195 sufficiently alleviates this problem?

**Comment by broady** [comment]
Yes!
