### ISSUE TITLE
Missing format methods for shared resource names

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#1861]
In languages that generate format and parse methods for configured resource names, we currently generate such methods on a particular client class only for resource names defined under the corresponding interface in the gapic config. This means that format/parse methods are omitted for resource names that are used in the interface, but defined outside of the interface section in the gapic config.

For example, BigQuery Data Transfer defines all resource name configurations at the top level, meaning no format or parse methods are generated for the DataTransferService interface.

**Comment by anthmgoogle** [comment]
Blocking a P1 issue.
