### ISSUE TITLE
Go: generated proto definitions should be in the package itself

### ISSUE THREAD

**Issue by broady** [googleapis/toolkit#190]
At the moment, a package like `github.com/googleapis/proto-client-go/pubsub/v1` needs to be imported. The type definitions from that package should be moved into the library gen.

We don't want people importing the types from another package.

**Comment by broady** [comment]
cc @jba @okdave @saicheems

**Comment by jba** [comment]
If we put the proto-gen code in the same package as the toolkit-gen code, the package will be a mess. It will refer to, e.g. RegisterLoggingServiceV2Server, even though the toolkit is just a client. Other symbols we don't want: NewLoggingServiceV2Client (the toolkit exports its own client which calls this for you), and any request or response proto for a method that has been configured to spread its args or return values.

We could just put the proto-gen package under the toolkit package. That might work for now. But I'd be worried about common types that are used by other APIs.

**Comment by broady** [comment]
Yes, we definitely don't want any of that. But at the moment, the user needs to import one that generated package just to access request structs.

**Comment by saicheems** [comment]
I don't mind particularly how ends up, but personally I quite like separating them

Some pros I can think of:
- The `go_package` values in the googleapis repo protos point to a path in another repo under the googleapis org. There may also be some value in giving users a separate path for compiled protos without importing gcloud itself
- Less clutter in the gocloud repo as Jonathan said - I think there's value in avoiding this clutter
- Other languages are separating protogen by means of packages (I realize Go differs in package distribution... and many cases)

**Comment by broady** [comment]
I talked to jba some more, and yes, I think this is not practical. I think I misunderstood the scope of VTK. It's more like a nice wrapper around gRPC, and not really like a fully hand-written library.

**Comment by broady** [comment]
However, we should import the pb package under a nicer name, for example logging is something like `google_api_logging_v2` but should probably be `loggingpb`. I'll file a separate issue for that tomorrow.
