### ISSUE TITLE
Python: Add module-level description to messages.snip template

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#196]
This ensures that when sphinx generates documentation for the API types, the module description is not blank.

We might use the template "Protocol buffer classes used by the Google {API Name} API".

**Comment by bjwatson** [comment]
See blank description for API Types in http://pythonhosted.org/gax-google-pubsub-v1/apis.html

**Comment by eoogbe** [comment]
@geigerj Is this still relevant?

**Comment by geigerj** [comment]
Not sure, re-assigning to @lukesneeringer to confirm the current status of Python GAPIC docs.

**Comment by eoogbe** [comment]
Closing because this code appears to be removed.
