### ISSUE TITLE
Go: provide GetPageSize for iterators

### ISSUE THREAD

**Issue by jba** [googleapis/toolkit#199]
This will help me implement exact pagination in handwritten iterators. (To do so I need to set the page size, and I want to restore the original page size.)

**Comment by saicheems** [comment]
Hmm, instead of providing both a getter and a setter, does it make sense to expose the iterator field?

**Comment by jba** [comment]
Not every iterator is going to need to expose page size. I just need it from the vkit. So let's just add a method.
