### ISSUE TITLE
Config Generator: "resource_field" should be "resources_field"

### ISSUE THREAD

**Issue by rok987** [googleapis/toolkit#202]
It appears that the config generator is creating the field "resource_field" using the singular noun "resource" when it should be the plural form "resources".

IMPACT
As a result, running the code gen fails since it doesn't recognize the singular form.

EXPECTED RESULT
We should generate the field "resources_field".

**Comment by michaelbausor** [comment]
Fixed in https://github.com/googleapis/toolkit/pull/207
