### ISSUE TITLE
Gapic: we are not handling the mixins

### ISSUE THREAD

**Issue by omaray** [googleapis/toolkit#203]
If an API yaml file (e.g. pubsub.yaml) contains more than one set of API in the "apis:" section, we fail to parse the yaml file correctly.

IMPACT
The code generator fails.

EXPECTED RESULT
We should be able to add support for mixins such as IAM (and others).

**Comment by bjwatson** [comment]
https://github.com/googleapis/toolkit/issues/430 addresses IAM specifically.

**Comment by eoogbe** [comment]
@garrettjonesgoogle Is this still relevant?

**Comment by garrettjonesgoogle** [comment]
Sounds done to me
