### ISSUE TITLE
Config Generator: generating duplicates in the collections part

### ISSUE THREAD

**Issue by rok987** [googleapis/toolkit#204]
The config generator creates the api_gapic.yaml file. In that file, we have the "collections:" section. It seems like we are sometimes duplicating some of the entries.

IMPACT
The code gen then fails to parse the config file correctly and no client library gets generated.

EXPECTED RESULT
There should be only one set of collection entries generated by the config generator.

**Comment by michaelbausor** [comment]
Fixed in https://github.com/googleapis/toolkit/pull/229
