### ISSUE TITLE
Package doc stuff

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#216]
If there is only one service, the service doc should go above the package declaration in `doc.go`.
I'd like to punt this for a little while - I'm starting to write a doc to address some open documentation questions between toolkit, gcloud, source protos, and other parties. I think it's all related enough that we should be looking for a bigger picture solution.

**Comment by saicheems** [comment]
@jba

**Comment by jba** [comment]
This all sounds good to me.

**Comment by bjwatson** [comment]
@saicheems Why did you remove the Go label?

**Comment by saicheems** [comment]
I don't think this issue is unique to Go, and I'd claim that for this issue Go codegen is WAI...
I left the issue open for tracking purposes, IMO it's better solved by clarifying what goes into the package/service class documentation in the proto than forcing it in codegen.
