### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#22]
@garrettjonesgoogle @bjwatson @anthmgoogle 

Should the package `io.gapi.vgen` become `io.gapi.gapic`? Or `io.gapi.codegen` (to avoid the stutter)?

**Comment by garrettjonesgoogle** [comment]
We shouldn't use "io.gapi" any more, that part should change to "com.google.api", so I'm thinking "com.google.api.toolkit" / "com.google.api.codegen" / "com.google.api.gapic"; although, this package does include discovery stuff, which technically falls outside of the realm of GAPIC, so maybe not the last one.

**Comment by pongad** [comment]
I actually think `gapic` is fine. The way I think about it, the two of them are so closely related -- at least by implementation -- that what we used to call `gapic` might as well subsume our work on Discovery.

**Comment by anthmgoogle** [comment]
Definitely not "vgen". I think "gapic" or "codegen" are fine and I'd go with "codegen" if you need a tie breaker.
Discovery seems odd with all 3 of these names to me, so this seems like a tangential issue.

**Comment by garrettjonesgoogle** [comment]
Related note, which was pointed out elsewhere: while we're at it, we should "lift" the contents of the `vgen` subproject to the toplevel of toolkit.

**Comment by garrettjonesgoogle** [comment]
The rename will be performed on Monday, May 9, to give everyone sufficient time to have their currently-open work submitted.

**Comment by garrettjonesgoogle** [comment]
As stated in other channels, the rename will happen Wednesday, May 11. 

Here are the renames/moves that I intend to make - let me know if any of them are objectionable, or if there are any other renames I should do:

* move vgen/* to the root /
* rename "io.gapi.vgen" to "com.google.api.codegen"
* rename "io.gapi.vsync" to "com.google.api.codegen.sync"
* rename &lt;prefix&gt;LanguageProvider to just &lt;prefix&gt;Provider
 * e.g. PythonGapicLanguageProvider => PythonGapicProvider
 * reasons:
   * In all of these class names, the name of the language (e.g. Python) is redundant with the Language part of the name.
    * "LanguageProvider" as a parent concept doesn't exist as a class.
    * A lot of class names will be shorter as a result.
* rename "&lt;language&gt;_discovery_gapic.yaml" to "&lt;language&gt;_discovery.yaml"
 * distinguishes discovery vs GAPIC

**Comment by garrettjonesgoogle** [comment]
Starting this now.

**Comment by garrettjonesgoogle** [comment]
Merged!
