### ISSUE TITLE
Too many blank lines in Discovery samples

### ISSUE THREAD

**Issue by bjwatson** [googleapis/toolkit#221]
For example, see https://cloud.google.com/compute/docs/reference/latest/autoscalers/delete#response. There are two blank lines between the PRE-REQUISITES comment and the import statements, and it looks like _four_ between the imports and class definition.

The Java style guideline (https://google.github.io/styleguide/javaguide.html#s3-source-file-structure) says that "_exactly one blank line_ separates each section that is present". I haven't checked the style guides for other languages, but they might have similar guidance.
- [x] Java
- [x] Go
- [x] Ruby
- [x] Python
- [x] PHP
- [x] Node

**Comment by pongad** [comment]
We introduced code formatting into jsonpkger which should eventually format everything nicely before putting them on the site.

Currently Go is complete and Java is underway. I made a checkbox in the issue description to keep track of this.

**Comment by bjwatson** [comment]
Looking much better!
