### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#242]
README.md says
> We currently support the generation of client code wrappers in three languages: Java, Python, C#.

This is not correct. We do have the code generator of Golang, Ruby, PHP, and Node.JS (also might be worth mentioning about samplegen?).

Probably we should review the README.md file and update the contents entirely?  It doesn't mention samplegen at all, for example.

**Comment by saicheems** [comment]
It seems everyone took action on the email at the same time haha

I updated the README to cover all languages (#241), but +1 to mentioning samplegen

**Comment by guokeno0** [comment]
Thanks :-)

-Jeff

**Comment by jmuk** [comment]
haha, thank you taking care of, @saicheems

**Comment by garrettjonesgoogle** [comment]
I'm closing this issue because we mention the GAPIC languages. Open another issue to mention sample gen if you wish, or just make the change...
