### ISSUE TITLE
Python samples' call format is incorrect

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#246]
Instead of
```
service.instances().insert(project, zone, instance)
```

the call should be
```
service.instances().insert(project=project, zone=zone, body=instance)
```

because Python methods have named arguments as documented by https://developers.google.com/resources/api-libraries/documentation/compute/v1/python/latest/compute_v1.instances.html

**Comment by tcoffee-google** [comment]
Fixed by https://github.com/googleapis/toolkit/pull/234
