### ISSUE TITLE
Properly format method parameter names in documentation

### ISSUE THREAD

**Issue by bjwatson** [googleapis/toolkit#253]
For example, see the Python documentation for logging `update_sink()` method: https://pythonhosted.org/gax-google-logging-v2/google.logging.v2.config_service_v2_api.html#google.logging.v2.config_service_v2_api.ConfigServiceV2Api.update_sink. The parameter name keys _are_ correctly formatted (snake-case), but references to the parameter names in the descriptions are still camel-case.

This problem might be more general than just Python, applying to other languages that use something other Java-style camel case for their method parameters.

Because this involves free text processing, we would need a solid heuristic for determining what tokens refer to parameter names. One possibility is any token that is wrapped in backticks and that contains any valid representation of any parameter name for a given method (e.g. `sinkName`, `SinkName`, `sink_name`, etc.).

**Comment by eoogbe** [comment]
This appears to be fixed
