### ISSUE TITLE
Java service level example does not handle list method

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#257]
If the first method in a service is a list method, the sample generated in the service documentation at the top of the file for that service will be incorrect.

**Comment by bjwatson** [comment]
@michaelbausor Is this Java-specific, or more general?

**Comment by michaelbausor** [comment]
This is Java only as far as I know, should have written this in the description, editted now.

**Comment by garrettjonesgoogle** [comment]
The code now picks the first flattened method, so this is fixed.
