### ISSUE TITLE
@extends is system-dependent

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#260]
In many of our templates, we `@extends "../common.snip"`. The `..` path is unique to UNIX-like systems.

Consequently, this fails when we package the project into a JAR file (JARs are ZIP archives, which do not support `..` directories). It will most likely fail on Windows as well.

There are a few ways to solve this problem.
- The most obvious is to not go into other directories. Keep in mind that path separators are also system-dependent, which means we cannot generally go into child directories either.

- We can make a change to api-compiler and find a way to normalize the "import path". For instance, we might say that `..` always mean parent directory and paths are always slash separated. We can then translate these strings to system-dependent forms. [A paper by Rob Pike](http://plan9.bell-labs.com/sys/doc/lexnames.html) touched on this topic. (Search for `Cleaning names`.) This approach does have its problems: For example, if someone put files in a `..` directory in a system where `..` does not mean parent directory, we won't be able to access it.

**Comment by pongad** [comment]
Curious to know what @garrettjonesgoogle thinks.

**Comment by garrettjonesgoogle** [comment]
Another option is to require files outside of the current package to be fully qualified, e.g. in py/common.snip you would have:

@extends "com/google/api/codegen/common.snip"

I'm a little uneasy about includes using '..' as a design principle; it restricts the modularity of the files.

**Comment by vchudnov-g** [comment]
The '..' also restricts modularity in a different way, but all things considered, I prefer Garrett's suggestion as to how to be explicit. This way, when we move a file it's easy to find all the places that reference it, whereas with parent directories it gets hairier
