### ISSUE TITLE
Enum documentation is incorrect

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#275]
In Python, the message name is not part of the enum's namespace. [See this example from the library baseline test.](https://github.com/googleapis/toolkit/blob/06514fa0171e1751d59677dabaa853e00ec5c1b8/src/test/java/com/google/api/codegen/testdata/python_message_library.baseline#L569)

**Observed:**
In the baseline test, we refer to the type:

```
:class:`google.example.library.v1.library_pb2.Book.Rating`
```
There is no documentation present for `Rating` itself.

**Expected:**
~~The actual, expected type is~~

~~`:class:`google.example.library.v1.library_pb2.Rating`~~

~~Also expect to see documentation detailing the possible values of `Rating`.~~

**Comment by geigerj** [comment]
I misunderstood the issue. The problem is that there is no generated Python type

`google.example.library.v1.library_pb2.Rating` or `google.example.library.v1.library_pb2.Book.Rating`

Rather, if `Rating` enumerates over {`GOOD`, `NEUTRAL`, `BAD`}, then the generated types are

`google.example.library.v1.library_pb2.Book.GOOD`

`google.example.library.v1.library_pb2.Book.NEUTRAL`

`google.example.library.v1.library_pb2.Book.BAD`

It's not immediately evident to me how we should document this. What we're doing right now is clearly not correct, since currently the generated docs refer to a nonexistent type.

We could list the enums as read-only attributes, but that seems misleading to me, since they're enums in spirit, not attributes. We could also give the type as

"Ratring enum (one of `google.example.library.v1.library_pb2.Book.{GOOD,NEUTRAL,BAD}`)"

but that also seems awkward.

@bjwatson @tbetbetbe thoughts?

**Comment by bjwatson** [comment]
Let's define constants in the surface that maps `...Book.GOOD` -> 0, `...Book.BAD` -> 1, etc. Then update documentation if needed to be accurate.
