### ISSUE TITLE
Improve bundling documentation

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#287]
Python bundling methods should
- include a sample showing the expected usage of the returned `Event` object
- give a full description of the return type in the docstring both for `Event` and protocol buffer types, depending on whether bundling is enabled or disabled

cc: @bjwatson @tbetbetbe

**Comment by bjwatson** [comment]
The priority of this really depends on whether we want to leave bundling enabled by default for any APIs (like Pub/Sub).

**Comment by eoogbe** [comment]
@geigerj Is this still relevant?

**Comment by geigerj** [comment]
Nope, we don't support bundling anymore. Closing as obsolete.
