### ISSUE TITLE
Let Proto3 decide defaults

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#307]
Let's not encode the proto3 defaults in the GAPIC generator -- we can just rely on proto to do this for us. This change has already been made to NodeJS/Ruby here: https://github.com/googleapis/toolkit/pull/306

**Comment by bjwatson** [comment]
@geigerj Does this affect the other four languages?

**Comment by geigerj** [comment]
@bjwatson I don't know; when I created the issue, it was specifically in reference to the fact that in the Python libraries, we do things like [setting integer fields to 0](https://github.com/googleapis/toolkit/blob/b4df82d87f0ebfa57f9c5b510be8dd6f37f45194/src/test/java/com/google/api/codegen/testdata/python_main_library.baseline#L711), which isn't really necessary, and it might slightly simplify the generator logic not to do this.

**Comment by geigerj** [comment]
I think it probably makes sense to keep the scope of this issue as Python-specific clean-up.

**Comment by geigerj** [comment]
This is actually blocking Pub/Sub snap-seek implementation, as setting the default for non-primitive types is not the same as leaving it unset. Bumping to P1.

cc: @lukesneeringer
