### ISSUE TITLE
GapicTestBase raises exception if the path has no "/"

### ISSUE THREAD

**Issue by shinfan** [googleapis/toolkit#308]
https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/GapicTestBase.java#L105

**Comment by bjwatson** [comment]
@shinfan Can you provide a little more detail on this issue? Does this affect all languages?

**Comment by shinfan** [comment]
At GapiTestBase.java L105:
String fileName = snippetFileName.split("\\.")[0].split("/")[1];

This assumes the snippetFileName contains a "/" char. (e.g. testdata/snippet.snip)
I don't feel this assumption is correct since it will cause an out-of-bound exception if the file name does not follow this pattern (e.g. snippet.snip).

**Comment by eoogbe** [comment]
@shinfan Is this still relevant?

**Comment by saicheems** [comment]
Doesn't appear to be relevant anymore.
