### ISSUE TITLE
configgen stops with NullPointerException if a service method doesn't have http option

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#316]
It seems that configgen crashes when running to a service which does not have `option(google.api.http)` specification in a method. An example is https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1/cloud_speech.proto

**Comment by pongad** [comment]
I ran into this issue a few minutes ago, but this confuses me. If the path isn't there, how does gRPC know where to send the request to...?

**Comment by pongad** [comment]
Because that's for HTTP, not gRPC. GAH!
