### ISSUE TITLE
add import check comments

### ISSUE THREAD

**Issue by jba** [googleapis/toolkit#321]
The go tool supports a check to make sure packages are "go get"ed from the right import path. This is a comment that comes after the package declaration. Add these comments to generated code. They only need to be in one file, so add them to doc.go. They should use the new cloud.google.com/go path.

E.g. logging/doc.go should be changed to
```
package logging // import "cloud.google.com/go/logging/apiv2"
```

**Comment by pongad** [comment]
@jba Sorry if I'm misunderstanding everything. Shouldn't the link be `google.golang.org/cloud/logging/apiv2`?

**Comment by pongad** [comment]
Nevermind, I just saw #320 :cry:
