### ISSUE TITLE
Sort out Go and Protobuf

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#324]
This is a meta-issue so we can specify the order in which issues regarding Go and Protobuf should be resolved. The primary goal of the issue is so that I don't do anything to upset the gopher god.

- [x] Document the existence of `google/go-genproto` in `googleapis/googleapis` README (https://github.com/googleapis/googleapis/pull/59)
- [x] Add deprecation warning to `googleapis/proto-client-go`, it's superseded by `google/go-genproto` (https://github.com/googleapis/proto-client-go/pull/7)
- [x] Delete Go-specific portions of `googleapis/googleapis/Makefile` (https://github.com/googleapis/googleapis/pull/60)
- [x] Update toolkit to point to `google/go-genproto` instead of `github.com/googleapis/proto-client-go` (issue: https://github.com/googleapis/toolkit/issues/312) (https://github.com/googleapis/toolkit/pull/327)
- [x] Regenerate `gcloud-golang` with the updated toolkit (https://code-review.googlesource.com/#/c/5401/)
- [x] Delete `googleapis/proto-client-go`

**Comment by pongad** [comment]
I reached out to @saicheems and he says the order looks reasonable. @broady @jba , can you verify?

**Comment by pongad** [comment]
@saicheems The regenerated logging client is merged. Can you help conform that `googleapis/proto-client-go` is safe to delete?

**Comment by saicheems** [comment]
Hmmm yeah, I think so!

**Comment by saicheems** [comment]
Oh wait, it's still part of gocloud-legacy... maybe we should leave it up until September 12th?

**Comment by saicheems** [comment]
If there are no objections, I'm going to delete the `proto-client-go` repo tonight.

**Comment by pongad** [comment]
@saicheems No objection from my side.

**Comment by saicheems** [comment]
Done
