### ISSUE TITLE
Wrong Import Path

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#329]
- [ ] `google.golang.org/genproto/googleapis/google/logging/v2` should be `google.golang.org/genproto/googleapis/logging/v2` without the `google` in the middle
- [ ] `google.golang.org/genproto/googleapis/api` should actually be `google.golang.org/genproto/googleapis/api/monitoredres` when importing MonitoredResources

This is most likely due to different file structure.

**Comment by jba** [comment]
Yes. In general, you want to replace /google/ with /googleapis/, not concatenate.  Also, there are more differences under the /api/ part of the tree.
