### ISSUE TITLE
Improve Go's Import Name Handling

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#339]
Go import name cannot rely on proto package, since Go's proto-created types are often placed in a different package structure.
https://github.com/googleapis/toolkit/pull/338 adds a workaround by special-casing the most common repository, but this is obviously not ideal.
I worked up a prototype solution at https://play.golang.org/p/vq9syre-ld . It will require MVVM to work however.

**Comment by jba** [comment]
What is MVVM?

I think it's probably easier to add go_package to the protos inside Google. That's already been done for some of the well-known types.

**Comment by bjwatson** [comment]
The refactoring that @garrettjonesgoogle is doing. The first version for PHP has already been merged (https://github.com/googleapis/toolkit/pull/317).

**Comment by pongad** [comment]
@jba When I said "import name" I meant the identifier that the package gets imported as, as in `import importName "import/path"`. The `"import/path"` portion is already set to be copied from the `go_package` option verbatim. Now the `importName` part should be based from the `go_package` option too, but not verbatim, since that would be way too long. Am I making any sense to you?

**Comment by jba** [comment]
@pongad OK, I see. 

But I don't understand why you need a suffix array to do this. How about:

1. Take the last component of the import path. If it's of the form "v[0-9]+", take the next-to-last component instead.
2. Make it unique by appending an integer (you only need a map[string]int for that).

**Comment by pongad** [comment]
@jba This is very true. The name clashing should be rare enough that appending integers should not hurt anything too badly. I was reading Knuth shortly before I wrote up this issue, so maybe I was just feeling extra algorithmy.

**Comment by pongad** [comment]
Superseded by https://github.com/googleapis/toolkit/pull/362
