### ISSUE TITLE
Support gRPC streaming methods

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#343]
We want to support gRPC-streaming methods in Gapic codegen eventually, this issue is tracking the effort for it.

https://github.com/googleapis/toolkit/issues/322 will be the first step -- removing them at all. Then, we can start supporting them language-by-language effort.

**Comment by jmuk** [comment]
Here will be the list of tasks.

- [ ] reveal response-streaming methods, as-is (i.e. interface is same as gRPC-gemerated ones)
- [ ] reveal request-streaming and bidi-streaming methods, as-is
- [ ] bring parameter-flattening / request-parameters for response-streaming method
- [ ] in case response stream actually iterates over chunks (i.e. chunk has a repeated field for actual resources), expand them as a stream of resources, as page-streaming does.

For request-streaming and bidi-streaming, it would be great to offer quite language idiomatic way to handle the input stream. For the time being, however, we will use the same interface as gRPC generates.

**Comment by garrettjonesgoogle** [comment]
@jmuk It's probably worth circling back here and determining what work remains still.

**Comment by jmuk** [comment]
Um. I feel like, basically I can close this, gRPC streaming is supported and works already (Sorry I've forgotten to close this).

There might be some chance to improve the existing surface, for example the one @chrisdunelm and you are discussing, but I think it's better to file an issue for each of such improvements.
