### ISSUE TITLE
Add a link to to public documentation in top-level API doc

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#358]
For example, API doc for Vision should probably have https://cloud.google.com/vision/docs/ link somewhere.

**Comment by eoogbe** [comment]
@pongad Is this still relevant?

**Comment by pongad** [comment]
Yup, still relevant. I'll assign to myself so this doesn't get lost.

**Comment by pongad** [comment]
Most repos added this to README, which is probably good enough. Will close this for now and reopen if it comes back up.
