### ISSUE TITLE
[Python] Incorrect imports for proto message that are not in the service proto file

### ISSUE THREAD

**Issue by bjwatson** [googleapis/toolkit#365]
Steps to Reproduce:

1) Generate surface for an API depending on proto messages outside of the API definition (need example)

Expected result: All import statements in the method samples should be complete and correct.

Actual result: All the import statements refer to messages in the service proto file, but nothing outside of it (confirm the exact behavior).

**Comment by eoogbe** [comment]
@bjwatson Is this still relevant?

**Comment by bjwatson** [comment]
Probably not. Let's create a new issue if we ever see this again.
