### ISSUE TITLE
Share method surface generation logic in test generator.

### ISSUE THREAD

**Issue by shinfan** [googleapis/toolkit#387]
Match or share the logic that determines the list of output methods:
https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/transformer/java/JavaGapicSurfaceTransformer.java#L270

**Comment by eoogbe** [comment]
@shinfan Are you still working on this?

**Comment by shinfan** [comment]
I feel this is now irrelevant. We have already shared the common logic under `TestCaseTransformer`. It is probably not worth refactoring the logic with the surface generation at this point.
