### ISSUE TITLE
Config generator should return meaningful error for invalid service config

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#425]
### To reproduce:

Run ConfigGeneratorTool with `--service_yaml` flag pointing to a service config that cannot be parsed by the tools framework (for example, by adding an unrecognized section).
### Expected behavior:

ConfigGeneratorTool checks `DiagCollector` after building its `Model`, and throws a meaningful exception if the collector has any errors. It should also report any other diagnostics that the `DiagCollector` has accumulated, even if building succeeds.
### Observed behavior:

Hard-to-debug stack trace with exception that occurs in the api-compiler, rather than toolkit.

```
ERROR: toplevel: Unexpected exception:
java.lang.NullPointerException
    at com.google.api.codegen.config.ConfigGeneratorApi.process(ConfigGeneratorApi.java:74)
    at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:85)
    at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:85)
    at com.google.api.codegen.config.ConfigGeneratorTool.generate(ConfigGeneratorTool.java:74)
    at com.google.api.codegen.config.ConfigGeneratorTool.main(ConfigGeneratorTool.java:62)

```

The null pointer is because the tools framework returns a null `Model` rather than throwing an exception if an error occurs during initialization; the errors must be retrieved from the `DiagCollector`.

/cc @shinfan

**Comment by geigerj** [comment]
On further investigation, the `ModelBuildResult` (from which the `Model` is drawn) [never propagates its diags if there is an error...](https://github.com/googleapis/api-compiler/blob/c6ae011a6075cfab3145b877a7c548447b704a24/src/main/java/com/google/api/tools/framework/tools/ToolDriverBase.java#L94) so it these errors get dropped before they ever make it to ConfigGeneratorTool. That's unfortunate because then we cannot check for errors during Model building. 

@the8bit -- is that interpretation correct? (That is the Model cannot be built, then at [this line](https://github.com/googleapis/api-compiler/blob/c6ae011a6075cfab3145b877a7c548447b704a24/src/main/java/com/google/api/tools/framework/tools/ToolDriverBase.java#L94), the Model is null, and so `this.diag` never gets access to the errors collected in the builder's DiagCollector, so the tool has no idea what error caused the failure.) If so, why do we want the `if (buildResult.getModel() != null)` condition at all?

**Comment by the8bit** [comment]
I think the if() is not needed, it should always just set  this.diags = buildResult.getDiagCollector();

This is probably a bug I introduced when pulling the model building logic out of ToolDriverBase. There was some funky coupling between model / DiagCollector in ToolDriverBase that I was working on fixing and this seems like collateral damage.

**Comment by geigerj** [comment]
Ok, let's change this internally and I can circle back to this once there's a new release of API compiler.

**Comment by eoogbe** [comment]
@geigerj Is this still relevant?

**Comment by geigerj** [comment]
I think this was fixed by https://github.com/googleapis/api-compiler/commit/c6d2d33609b60241db80a4015cb0b91b45b28fac. If not, it should probably be tracked in the `api-compiler` repo, rather than here.
