### ISSUE TITLE
Implement reroute_to_grpc_interface for all languages (Pub/Sub IAM)

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/toolkit#430]
This functionality enables IAM for Pub/Sub.

Java/PHP were implemented in https://github.com/googleapis/toolkit/commit/b92d62397e895df0880fa982071a80f117c066c3 .
- [x] Node.js
- [x] Ruby
- [x] Python
- [x] Go
- [x] C#

@jmuk @bjwatson @chrisdunelm @saicheems @pongad

**Comment by jmuk** [comment]
cc: @Landrito

**Comment by jmuk** [comment]
not closing entirely 😉

**Comment by Landrito** [comment]
Thanks for catching this. Forgot merging would automatically close this.

**Comment by bjwatson** [comment]
Parent issue is https://github.com/googleapis/toolkit/issues/203

**Comment by bjwatson** [comment]
@Landrito Use the phrasing "Updates X" when a PR is not a complete fix.

**Comment by bjwatson** [comment]
@Landrito Use "Updates" rather than "Fixes" when your PR is not a complete fix for this issues. In this case, it only fixes Python.

**Comment by Landrito** [comment]
Ah I see. Will do!

**Comment by pongad** [comment]
@garrettjonesgoogle Will using MVVM automagically fix this? The test method showed up in my go-mvvm branch. I'm not sure if there's anything else I have to do.

**Comment by garrettjonesgoogle** [comment]
@pongad you have to make sure that the method uses the right stub. The AddLabel method should use LabelerGrpc instead of LibraryServiceGrpc. You will have some kind of work to do based on how your language makes calls to the right stub.

**Comment by pongad** [comment]
This is finished in Go, updated the message accordingly.

**Comment by chrisdunelm** [comment]
This was done in C# a while ago. I only just noticed this outstanding bug.
Looks like all languages are now done, so I'll close the bug.
