### ISSUE TITLE
nodejs_doc generated doc file path is incompatible with others

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#437]
Observation:

When generate the pubsub API with nodejs_doc ID, the generated file structure is as follows:
- src/v1/publisher_api.js
- src/v1/publisher_client_config.js
- src/v1/subscriber_api.js
- src/v1/subscriber_client_config.js
- src/doc_google_protobuf_timestamp.js
- src/doc_pubsub.js

What's expected:

Those 'doc_' files should be in the same `src/v1` directory.

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
