### ISSUE TITLE
Ruby: allow delay loading of grpc module

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#446]
Current structure of generated file always load dependency at the toplevel of the file. Therefore, when a ruby script has a statement like
```ruby
require "google/cloud/pubsub/v1/publisher_api"
```
this implicitly loads `publisher_service_pb` (grpc-generated file) which implicitly loads `grpc` which initializes the module.

According to https://github.com/grpc/grpc/issues/7951,
> Currently, forking after initializing grpc is not supported

So this will be problematic. We should delay loading required module as far as possible.

**Comment by blowmage** [comment]
I'm fine with the process as-is. I have a [potential change to google-cloud-ruby](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/875) that will allow us to create protobuf objects without loading the service classes and the GRPC library. I _think_ this will help relieve some pressure our users working in a forked environment (like a rails app using Puma).
