### ISSUE TITLE
Don't overwrite user's metadata

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#474]
Currently, we do this at the beginning of every method:
```
ctx = metadata.NewContext(ctx, c.metadata)
```
where `c.metadata` contains the version of the client library.

However, this will nuke any metadata that already exists in the context. We should be adding to it instead.

cc @jba @garye

**Comment by liujiongxin** [comment]
How is the fix going?

**Comment by pongad** [comment]
@liujiongxin This fix is currently scheduled to go out after https://github.com/googleapis/toolkit/pull/465 (which, despite its name, should finalize pretty soon). Please let me know if you cannot wait until then.

**Comment by liujiongxin** [comment]
Thanks for scheduling the fix work. It's not an urgent thing for me, but I'm glad to adapt my current code to the fix.
