### ISSUE TITLE
Stop using beta entry point to gRPC generated code for gRPC stubs

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#481]
### What

Replace this line

https://github.com/googleapis/toolkit/blob/619640e579d564ad131410c9975a2e6f2b8ec8b9/src/main/resources/com/google/api/codegen/py/main.snip#L239

with a non-beta entry point. This may require changes to GAX, and the signature of the constructor non-beta `XXXStub` generated class seems to differ from the beta method.

### Why

Makes codegen compatible with `python-gax 0.13.0` and ensures that we consistently use a gRPC 1.0 surface across GAPIC and GAX.

**Comment by geigerj** [comment]
/cc @bjwatson 

See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2258 for further discussion of incompatibility between current codegen and `python-gax 0.13.0` due to this issue.

**Comment by bjwatson** [comment]
@geigerj This is fixed by https://github.com/googleapis/toolkit/pull/483, right?

**Comment by geigerj** [comment]
Yup, not sure why it didn't auto-close...

**Comment by bjwatson** [comment]
You didn't have a "Fixed:" link in your PR. I added one a few minutes ago, but it was after the merge, so it didn't do anything

**Comment by bjwatson** [comment]
Anyway, thanks for fixing this!
