### ISSUE TITLE
Allow CommonGapicCodePathMapper to choose path name format for different languages.

### ISSUE THREAD

**Issue by swcloud** [googleapis/toolkit#484]
getOutputPath should return lower_underscore path name for Ruby.

**Comment by garrettjonesgoogle** [comment]
Instead of creating a subclass, I would prefer to parameterize CommonGapicCodePathMapper with the desired casing treatment of the package and use that for Ruby.

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
