### ISSUE TITLE
Adding more Interfaces can break Go surface

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#486]
Go has a logic to drop the name of the service from client type names:
The client name for `LibraryService` is just `Client`, not `LibraryClient`.

This happens in two cases
- The service is the only service defined
- The service has the same name as the package name

The first case will break the API if a second service is added to the package. Maybe we should only drop the service name in the second case?

cc @jba

**Comment by jba** [comment]
Good point.

I suppose an API could add a second service without bumping their major version number.

So I think you're right: just because the service is the only one in the API, doesn't mean we can shorten the name.

/cc @okdave @zombiezen

**Comment by zombiezen** [comment]
👍  for removing first case and keeping the second.  Seems more consistent with the [Effective Go guidance](https://golang.org/doc/effective_go.html#package-names).

**Comment by pongad** [comment]
Closed by https://github.com/googleapis/toolkit/pull/522
