### ISSUE TITLE
DiscoveryImporter investigation items

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#494]
DiscoveryImporter doesn't parse the method parameters of storagetransfer.getGoogleServiceAccount

Should have 1 parameter: `projectId`
Actually has none.

**Comment by tcoffee-google** [comment]
Current workaround is override in src/test/java/com/google/api/codegen/testdata/discoveries/storagetransfer.v1.json.overrides ... can be removed if resolved.

**Comment by saicheems** [comment]
Also investigate why `DiscoveryImporter` produces `DatasetList.Datasets` instead of `Dataset` for the page streaming resource of the `bigquery.datasets.list` method.

**Comment by saicheems** [comment]
(And is there a rule we can find that allows us to produce DatasetList.Datasets in Java/C# and Dataset in other languages)

**Comment by saicheems** [comment]
Obsolete, guess it was an out of date library issue.
