### ISSUE TITLE
Build fails with parameter names which are keywords

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#495]
In `Google.Devtools.Clouderrorreporting` we end up with generated code like this:

```
public virtual ReportErrorEventResponse ReportErrorEvent(
    string projectName,
    ReportedErrorEvent event,
    CallSettings callSettings = null)
{
    throw new NotImplementedException();
}
```

This fails to compile as `event` is a keyword. It either needs to be specified as a verbatim literal (`@event`) or with underscores etc.

**Comment by chrisdunelm** [comment]
This was fixed a while ago in #710.
