### ISSUE TITLE
GAPIC samples: support subfield and optional parameter init values

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#496]
### What

Currently Python GAPIC samples only initialize top-level fields on the request message that are marked as "required". This feature request is to enable initializing optional fields and subfields (i.e., fields of message fields).
### Why

Samples are more helpful when they mirror actual use. Some API calls in practice require complex initialization of the request message, and in these cases, our generated samples are not as helpful as they should be. (See, for example, [cloud vision](https://github.com/googleapis/api-client-staging/blob/master/generated/python/gax-google-cloud-vision-v1/google/cloud/vision/v1/image_annotator_api.py#L125).)
### How

Assuming that Python is not yet on the MVVM architecture:
- Modify PythonImportHandler for snippets to read the init values from config and add their imports, [instead of relying on required fields](https://github.com/googleapis/toolkit/blob/78477f5f28e5f1e4fc4fe32552b8084d0e19004a/src/main/java/com/google/api/codegen/py/PythonImportHandler.java#L104).
- Verify that [method_sample.snip](https://github.com/googleapis/toolkit/blob/78477f5f28e5f1e4fc4fe32552b8084d0e19004a/src/main/resources/com/google/api/codegen/py/method_sample.snip) can pick up optional fields and subfields to be initialized from the GAPIC config.

/cc @bjwatson @Landrito

**Comment by eoogbe** [comment]
@geigerj @lukesneeringer Is this still relevant?

**Comment by geigerj** [comment]
The sample generator handles subfields now ([test example](https://github.com/googleapis/toolkit/blob/6d55c9ce9cb1cc636797da9b8253283fb9c911fb/src/test/java/com/google/api/codegen/testdata/py/py_library.baseline#L1934)), so I don't think so.
