### ISSUE TITLE
Don't generate identifiers that are reserved keywords

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/toolkit#550]
When creating the Go samples for the drive API, we generate this gem:

```
// The A1 notation of the values to update.
  range := "{MY-RANGE}"
// TODO: Change placeholder value above.
```

which does not compile because `range` is a keyword. We should ensure none of our generated identifiers are keywords.

Solution
1. Short-term: tcoffee@ please add an exception for this particular case in the Go generator, with a TODO to build a more scalable solution
2. Short-term: saicheems@ port this exception when doing the Go MVVM refactoring
3. saicheems@, tcoffee@: Please design and implement a longer term solution (on the MVVM-based code) where we check all generated identifiers against that language's keywords, and modify them if there's a collision.

**Comment by saicheems** [comment]
The long term solution for this (done for Java in #556) is to seed the symbol table with reserved identifiers.

**Comment by vchudnov-g** [comment]
@saicheems Sweet! That will take care of #2 and #3. @tcoffee-google , we still need to do #1 in the meantime.

**Comment by tcoffee-google** [comment]
#1 should be resolved by https://github.com/googleapis/toolkit/pull/567, but please check since Cloud baselines are unchanged.

**Comment by tcoffee-google** [comment]
Additional cases handled in https://github.com/googleapis/toolkit/pull/588.
