### ISSUE TITLE
Get UX input on commented code in generated samples

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#552]
Currently, discovery client library samples suggest optional code (for media upload/download) as comments offset by blank lines at the current indentation. @vchudnov-g suggests visually offsetting commented code by indents instead of blank lines: https://github.com/googleapis/toolkit/pull/542#discussion_r81198302

**Comment by saicheems** [comment]
Have we done this? There doesn't seem to have been any negative feedback yet, anyway

**Comment by tcoffee-google** [comment]
I think it would make sense to get some proactive user feedback once other P1 fixes for correctness are submitted.

**Comment by vchudnov-g** [comment]
None of the changes since MVVM have been published yet....

**Comment by saicheems** [comment]
I think we should claim wontfix or say that we're at a good enough point on this, I think we've gotten a significant amount of input from language experts, that may be enough to close this one.

**Comment by tcoffee-google** [comment]
AFAICT, we have not made a full update of live samples since last summer, and some of the samples specifically relevant to this issue are not live; so absence of negative feedback may not be indicative. I think once we have a fully passing set of samples, it would still make sense to get a final round of user feedback of some kind.

**Comment by vchudnov-g** [comment]
Demoting to P2 because of other priorities.

**Comment by eoogbe** [comment]
@tcoffee-google @vchudnov-g  Is this still relevant?

**Comment by saicheems** [comment]
Unlikely to happen at this point, closing.
