### ISSUE TITLE
Update Discovery samplegen Ruby names files

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/toolkit#554]
The Discovery samplegen names file is out of date. Let's fix it manually to unbreak samplegen ASAP.

A more sustainable fix is being tracked in #553.

**Comment by vchudnov-g** [comment]
@tcoffee-google: Was this fixed by #555 or is there something else to do, short-term?

(Let's keep the issues up to date and linking to the corresponding PRs)

**Comment by tcoffee-google** [comment]
I think the update will have to be done again because we need to update the replicapoolupdater discovery doc for our Java compile check to pass.

**Comment by vchudnov-g** [comment]
OK, just keep cross-mentioning the PRs and this issue so we keep track,

**Comment by tcoffee-google** [comment]
Per offline discussion, we probably won't bother with more manual updates until we resolve #553, so I will mark this closed by #571.
