### ISSUE TITLE
Scope list is wrong in Go discovery samples

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#558]
```
// TODO: Change placeholder below to get authentication credentials.
// See: https://foo.com/bar
//
// To use the `Get` method, authorize using one of the following scopes:
//   AdexchangeBuyer
```

Is correct in `disco_head`, so I figure something happened in #487 
Probably just using the wrong variable in the snippet or something, all the other languages seem to be correct

**Comment by vchudnov-g** [comment]
@tcoffee-google, could you take a look?

**Comment by tcoffee-google** [comment]
Yes, a refactor in DiscoveryContext was coincidentally overridden in GoDiscoveryContext (an example motivation for Override enforcement in Java). Fixed in https://github.com/googleapis/toolkit/pull/568.
