### ISSUE TITLE
Allow <X>Api class to accept a channel parameter

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#561]
Once this is supported by gRPC, accept a channel parameter as part of the optional argument array used to construct the <X>Api class

**Comment by eoogbe** [comment]
@michaelbausor Is this still relevant?

**Comment by michaelbausor** [comment]
This was actually closed just a few hours ago in https://github.com/googleapis/toolkit/pull/1454, thanks for the ping! :-)
