### ISSUE TITLE
Make new major version of ConfigProto

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/toolkit#563]
When we get to the point where we need to make breaking changes to ConfigProto, we might want a new major version, since we have accumulated a bunch of GAPIC config at this point. Pending breaking changes:
1. Move from `com.google.api.codegen` to `com.google.api.codegen.config`

**Comment by eoogbe** [comment]
@garrettjonesgoogle Is this still relevant?

**Comment by garrettjonesgoogle** [comment]
no
