### ISSUE TITLE
Support custom prefix for identifiers that conflict with reserved identifiers in Discovery

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#564]
`int` -> `resourceInt` instead of `int2`.

The semantics are up for debate - I would fix this by:

```
public SymbolTable(String conflictPrefix) {
  this.conflictPrefix = conflictPrefix;
}

public String getSymbol(String name) {
  if (RESERVED_IDENTIFIER_SET.contains(name)) {
    return conflictPrefix + name + getSuffix(name);
  }
  ...
}
```

Basically, a prefix for names conflicting with reserved identifiers that is decided when the table is constructed. That could be the last methodNameComponent, or anything really.

**Comment by saicheems** [comment]
@tcoffee-google 
@vchudnov-g

**Comment by tcoffee-google** [comment]
Examples of poor results from collision resolution not involving a reserved identifier:
https://github.com/googleapis/toolkit/pull/696#discussion_r86038358
https://github.com/googleapis/toolkit/pull/696#discussion_r86038919

**Comment by saicheems** [comment]
I believe the right move here is to either support prefixes or suffixes in the `SymbolTable` or introduce language specific `SymbolTable`s

**Comment by tcoffee-google** [comment]
For reference, a more generic example: AppEngine services list method (collision on `service`).

**Comment by saicheems** [comment]
Seems like most languages would prefer an `_` collision prevention to a numeric scheme. I think the best course is to add a flag to the `SymbolTable` constructor that decides which method to use.

**Comment by saicheems** [comment]
#739

**Comment by tcoffee-google** [comment]
As noted in https://github.com/googleapis/toolkit/pull/846#discussion_r93086655, it might be worth having special handling for the case of iterator variables, where numeric renaming produces a confusing result (like examples in https://github.com/googleapis/toolkit/issues/564#issuecomment-257925186)

**Comment by eoogbe** [comment]
@saicheems Is this still relevant?

**Comment by saicheems** [comment]
Current situation is fine, really.
