### ISSUE TITLE
Node: do not name the anonymous function set on the prototype of service objects.

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#573]
### What
Naming the anonymous function set on the prototype of a service object is not idiomatic.

### Example
https://github.com/googleapis/api-client-staging/blob/master/generated/nodejs/google-cloud-node/packages/monitoring/src/v3/metric_service_api.js#L292

### Expected
```js
// Change this...
Service.prototype.methodName = function methodName() {

// into this.
Service.prototype.methodName = function() {
```

**Comment by landrito** [comment]
cc @jmuk

**Comment by jmuk** [comment]
I inherited this design from packman, and I've heard that the benefit of this design is that a stack trace can record a name of the function with the current style while the new style can't.

However, as I tried locally (with node v4.2.3), it seems no change on the stack trace of errors. Let's do this.

**Comment by landrito** [comment]
Interesting! Thanks for checking the stack trace! :)
