### ISSUE TITLE
Auto-synchronize discovery sample generator, compile check, and client libraries

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#587]
[DRAFT; note this generalizes #84]

Currently, any update to a discovery doc for a sample-generated API can typically break both language client libraries and sample-gen compile check. It appears that even a substantial fraction of effort by the sample-gen team is insufficient to maintain synchronization using the current process; indeed, despite multiple weeks of focused effort, such synchronization has yet to be achieved even once. We need a more automated process.
# Objectives

In the current process, each of the following paths require a separate manual initiation and/or review to propagate updates:

| From | To |
| --- | --- |
| live discovery doc | live client library repo 1 |
| live discovery doc | live client library repo 2 |
| ... | ... |
| live discovery doc | live client library repo 7 |
| live discovery doc | toolkit repo test discovery doc |
| toolkit repo generator | gapi-cmds repo compile checker |
| toolkit repo test discovery doc <br /> toolkit repo generator | toolkit repo test samples |
| toolkit repo test discovery doc <br /> toolkit repo generator <br /> gapi-cmds repo compile checker <br /> live client library repos 1-7 | toolkit repo test compile check 1-7 |
| live discovery doc <br /> toolkit repo generator <br /> gapi-cmds repo compile checker <br /> live client library repos 1-7 | live samples <br /> live compile check 1-7 |

This unnecessarily large set of paths inevitably leads to numerous inconsistencies. These paths can be simplified to serve only the following needs:

For users:
(a) keep live client libraries consistent with live discovery sources (representing API backends)
(b) keep live samples consistent with live client libraries
(c) preserve individual sources for client libraries in each language

For developers:
(d) iteratively test changes to generator, compile checker, and/or client libraries against static tests (i.e., without updating discovery sources)
(e) keep test client libraries consistent with test discovery sources in above iteration
(f) keep static tests periodically consistent with live discovery sources as development iteration allows
(g) incorporate external contributions to individual client libraries in each language

The proposed process involves only 3 update paths, which meet the needs above as indicated:

| Path | From | To |
| --- | --- | --- |
| 1 (e, f) | live discovery doc | toolkit repo test discovery doc <br /> toolkit client library **sub**repos 1-7 |
| 2 (d) | toolkit repo test discovery doc <br /> toolkit repo generator <br /> ~~gapi-cmds~~ toolkit repo compile checker <br /> toolkit client library **sub**repos 1-7 | toolkit repo test samples <br /> toolkit repo test compile check 1-7 |
| 3 (a, b, c, g) | live discovery doc <br /> toolkit repo generator <br /> ~~gapi-cmds~~ toolkit repo compile checker <br /> toolkit client library **sub**repos 1-7 | live samples <br /> live compile check 1-7 <br /> live client library repos 1-7 |

Path 3 could be initiated automatically once the sample-gen infrastructure has sufficiently matured, further improving consistency for users.
# Implementation

The above paths can be implemented with two structural changes to the current codebase:
1. Move compile checker from gapi-cmds repo into toolkit repo
2. Incorporate client library repos as **sub**repos of toolkit repo using the git-subrepo tool.

The git-subrepo tool is a mature wrapper around native git functionality that allows push and pull from subtrees of a repository to independent external repositories. It solves the major problems associated with git submodules and the older git subtree tool: https://github.com/ingydotnet/git-subrepo

![samplegen versioning refactoring](https://user-images.githubusercontent.com/16905211/27192934-fa4fab6e-51b1-11e7-9265-20be7f048bf3.png)

**Comment by vchudnov-g** [comment]
Let's move this discussion to an internal doc instead. Please create one, or better yet, add onto go/vkit-snippetgen-tests, which is trying to deal with testing issues.

**Comment by eoogbe** [comment]
@vchudnov-g What was the conclusion of the internal doc?

**Comment by saicheems** [comment]
This is in progress, client libraries are almost all automatically updated, I'll close when that's done.
