### ISSUE TITLE
Multiple oneof fields are being set 

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#591]
### What

`oneof` is intended to represent a single field, yet in the Python generated code appears as multiple fields, only one of which may be set at any time. In the current Python codegen, we are setting multiple of these. For example, there might be a proto request:

```
message ListFooRequest {
  ...
  oneof msg {
    string oneof1 = 17;
    string oneof2 = 18;
  }
}
```

which would generate

```
def list_foo(..., oneof1='', oneof2=''):
  request = ListFooRequest(..., oneof1=oneof1, oneof2=oneof2)
```

This is incorrect.

### Why

Setting a oneof to its proto3 default value is *not* the same as not setting it. Instead, we should only set oneof fields in the generated proto class if they are set in method parameters:

```
def list_foo(..., oneof1=None, oneof2=None):
  if oneof1 is not None:
    request = ListFooRequest(..., oneof1=oneof1)
  if oneof2 is not None:
    request = ListFooRequest(..., oneof2=oneof1)
```

This gets messy if there are multiple oneofs in a message (# lines of code is exponential in the number oneofs), but we can clean this up by letting GAX do the work in a utility function that constructs the oneof args:

```
def list_foo(..., oneof1=None, oneof2=None):
    oneof_args = gax.oneof_args(ListFooRequest, oneof1=oneof1, oneof2=oneof2)
    request = ListFooRequest(..., **oneof_args)
```

cc: @bjwatson

**Comment by geigerj** [comment]
On second look, it seems that passing `None` to the constructor is sufficient, i.e.,

```
ListFooRequest(oneof1=None, oneof2='abc')
```

is the same as

```
ListFooRequest(oneof2='abc')
```

If that is the case, a much simpler solution is just to make the default value of all oneofs `None` -- no need to create helpers in GAX.

**Comment by bjwatson** [comment]
@dhermes thought that even passing `None` might be a problem, but he wasn't sure about that. If you've tested it and it's okay, then using `None` for unspecified arguments sounds like the easiest solution.

**Comment by dhermes** [comment]
@bjwatson This was the snippet I used previously:

```python
>>> from google.cloud.bigtable._generated import table_pb2
>>> from google.protobuf import duration_pb2
>>> duration = duration_pb2.Duration()
>>> gc_rule = table_pb2.GcRule(max_num_versions=42, max_age=duration)
>>> gc_rule
max_num_versions: 42

>>> gc_rule.WhichOneof('rule')
'max_num_versions'
```

to test the explicit `None` is as simple as

```python
>>> gc_rule = table_pb2.GcRule(max_num_versions=None, max_age=duration)
>>> gc_rule
max_age {
}

>>> gc_rule.WhichOneof('rule')
'max_age'
```

Note that the explicit `None` is happily ignored in that case.

**Comment by bjwatson** [comment]
Awesome! Thanks @dhermes.
