### ISSUE TITLE
Overrides files cleanup: directory, extension

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/toolkit#602]
- The overrides files are used in production, not just in tests, so they should be moved out of the testdata directory.
- The overrides files are valid json, so maybe instead of being of the form `api.version.json.overrides` they should be `api.version.overrides.json`. This will require slightly more processing on the calling side, but not much (in bash: using `%` in variable substitution; in Go, stripping the extension returned by path.Ext())

**Comment by saicheems** [comment]
Submitted an issue under discovery-artifact-manager for the first item. The overrides in toolkit should eventually only be used to ensure the baselines are generated as expected.
