### ISSUE TITLE
gapic generated code should add 'require xxx_pb.rb'

### ISSUE THREAD

**Issue by swcloud** [googleapis/toolkit#610]
Due to a restriction in grpc module loading (they need to be delayed until after the gapic module is loaded). This will cause the reference to the protobuf classes (such as those in pubsub_pb) is not available until the corresponding API service classes (such as publisher_api) are initialized. As a result, we have some order restriction in terms of how the API is called. The solution is that we should load the protobuf classes from the API service classes directly instead of counting on protobuf service classes (such as pubsub_services_pb)

**Comment by bjwatson** [comment]
I added the P1 label, since this is blocking Beta.

**Comment by landrito** [comment]
Will be resolved by #613.
