### ISSUE TITLE
Possible end of block comments not being detected.

### ISSUE THREAD

**Issue by landrito** [googleapis/toolkit#615]
### What

Some proto-file comments are causing `/* */` style block comments to end preemptively.
### Example Comment

From [LRO operations.proto](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto#L50)

``` proto
  // NOTE: the `name` binding below allows API services to override the binding
  // to use different resource name schemes, such as `users/*/operations`.
```

The `users/*/operations` comment causes any block comment it is inside to end.
### Example Gapic Output

Node:

``` js
/**
 * Lists operations that match the specified filter in the request. If the
 * server doesn't support this method, it returns `UNIMPLEMENTED`.
 *
 * NOTE: the `name` binding below allows API services to override the binding
 * to use different resource name schemes, such as `users/*/operations`
 *
 * @param {Object} request
 *   The request object that will be sent.
 * @param {string} request.name
 *   The name of the operation collection.
 * @param {string} request.filter
 *   The standard list filter.
 *  . . .
 */
```

**Comment by landrito** [comment]
cc @garrettjonesgoogle @michaelbausor @jskeet @pongad since java, php, c#, and go also use block `/* */` block comments.

**Comment by jskeet** [comment]
@chrisdunelm

**Comment by landrito** [comment]
Thanks Jon!

I looked through the generation of languages that also use `/* */` style block comments. It seems that C# uses `///`, go uses `//`, and java does some comment filtering so their attention might not be needed.

**Comment by eoogbe** [comment]
@landrito Is this still relevant?

**Comment by chrisdunelm** [comment]
This is not an issue for C#

**Comment by eoogbe** [comment]
What about in NodeJS and PHP?

**Comment by landrito** [comment]
This is still relevant for Node.js.

**Comment by eoogbe** [comment]
@landrito Can you add a priority?

**Comment by landrito** [comment]
Done.

**Comment by michaelbausor** [comment]
This is not an issue for PHP as we escape the close comment sequence. In case it is helpful for Node, the code is here: https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/util/php/PhpCommentReformatter.java#L28
