### ISSUE TITLE
Do not generate `PagedResponseWrapper` class if it is empty.

### ISSUE THREAD

**Issue by shinfan** [googleapis/toolkit#617]
Example: https://github.com/googleapis/api-client-staging/pull/81/files/fe1d19f26bc489f52b451b1d7feb535f86ea8014#diff-ddd5488c9432bee7b028fdd3ce10cfe3

**Comment by garrettjonesgoogle** [comment]
This is done already, right?

**Comment by shinfan** [comment]
Yes, this should be done.
