### ISSUE TITLE
Language-independent one-of fixes

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#620]
### What
- Do not mark oneofs as required or flattened in the GAPIC config generator.
- Warn in GAPIC codegen if a oneof is marked as required.
- Warn in GAPIC if multiple values of a oneof are flattened in a single output method.
### Why
- Any of the above scenarios can lead to invalid requests if multiple possible values of the oneof get set.

**Comment by swcloud** [comment]
@geigerj @bjwatson @danoscarmike Will this affect surface generation?

**Comment by geigerj** [comment]
@swcloud No, the scope of this issue is limited to the default GAPIC config we generate, and to emitting warnings in GAPIC if we encounter suspect configuration for oneofs. For all current APIs, AFAIK, we've already manually configured oneof fields not to be required.

**Comment by eoogbe** [comment]
@geigerj Can we get a priority on this?
