### ISSUE TITLE
Allow multiple `domain_layer_location`s

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#623]
For context, see https://github.com/googleapis/googleapis/pull/172

**Comment by eoogbe** [comment]
@pongad Is this still relevant?

**Comment by pongad** [comment]
I think we should leave this here for now. Thank you for taking a look!

**Comment by eoogbe** [comment]
Can you add a priority?

**Comment by pongad** [comment]
So far this is not needed. I'll close this out for now and reopen if it comes up again.
