### ISSUE TITLE
Allow specifying non-default authentication

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#628]
gax-ruby currently supports optional `updater_proc` argument, and skips `Google::Auth.get_application_default` when specified (see https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax/grpc.rb#L77).

However, our code generator does not specify this parameter at all, so this means nothing. In order to support non-default credentials (like OAuth2 credentials), this is a bit problematic.

Theoretically this can be done by creating its own gRPC channel and specifying it through `channel` param, but this isn't very friendly for those who only wants to customize the authentication path.

Suggestion:
- Add optional `credentials` parameter to the constructor of the codegen
- Invokes with `credentials.updater_proc` for `create_stub` when `credentials` is specified

cc: @swcloud @landrito 

Also -- @bjwatson @geigerj in case similarity happens on Python.

**Comment by jmuk** [comment]
@anthmgoogle @vchudnov-g FYI.

**Comment by bjwatson** [comment]
@jmuk Is this a Ruby-only issue, or do we expect it to affect other languages also?

**Comment by jmuk** [comment]
not sure. I'm feeling like potentially the same thing could happen on Python, but didn't verify. NodeJS is probably less problematic because it depends on a different library `google-auto-auth`.

**Comment by eoogbe** [comment]
@geigerj Can you check if this is still relevant?

**Comment by landrito** [comment]
This is no longer relevant. Closing.
