### ISSUE TITLE
Move Java auto-format from generation path to test path

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#631]
Currently Java discovery samples are auto-formatted with google-java-format before publication, which can lead to unintended results (cf. https://github.com/googleapis/toolkit/pull/629).

Instead, the formatter should run in verification mode as part of testing, so any conflicts with Google Java style can be individually reviewed. To avoid failures due to long qualified names, the formatter might be configured with a long maximum line length.

**Comment by saicheems** [comment]
Thoughts on this one? I'm thinking wontfix

**Comment by tcoffee-google** [comment]
I suggest demoting to P3, behind feature changes.
