### ISSUE TITLE
Handle Hash to Protobuf.Map conversion for Ruby

### ISSUE THREAD

**Issue by swcloud** [googleapis/toolkit#639]
This fixes [#45](https://github.com/googleapis/gax-ruby/issues/45)

**Comment by swcloud** [comment]
@jmuk Can this be a quick fix from you?

**Comment by jmuk** [comment]
I could do but that would be a good task to learn about the code generation. I like someone else to do that.
(by the way, I think you don't have to file this as a separate issue, just keeping googleapis/gax-ruby#45 is fine).

**Comment by blowmage** [comment]
I think this issue can be addressed in the GAPIC generated code, but I can also see this being fixed in google/protobuf, since it appears that is where the bad behavior originates.
