### ISSUE TITLE
Remove duplicate `ID` suffix from the paramter name

### ISSUE THREAD

**Issue by shinfan** [googleapis/toolkit#644]
Reference Link: https://github.com/shinfan/toolkit/blob/95544a822b2b70173df65ffc900e0527c9ade180/src/test/java/com/google/api/codegen/testdata/csharp_gapic_client_library.baseline#L715

**Comment by chrisdunelm** [comment]
Examples of this bug have moved: https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/csharp_gapic_resourcenames_library.baseline#L77
