### ISSUE TITLE
Construct synthetic API for comprehensive testing of discovery sample gen

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#648]
A synthetic API could replace redundant baseline coverage in toolkit by exercising all known features of the discovery sample gen transformers. This would obviate #201.

To aid such development, the following **incomplete** list serves to record test elements that might otherwise be overlooked:
- formatting of Go Download method links with multipart resource paths (#645)

**Comment by saicheems** [comment]
May not have bandwidth for this item anymore :(
