### ISSUE TITLE
Gofmt for Discovery

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#65]
Go Discovery code samples and client libraries should be formatted with gofmt.

**Comment by vchudnov-g** [comment]
And we should auto-format in other languages too, where possible.

**Comment by saicheems** [comment]
Did we start doing this? I think the regular codegen is formatted, not sure if discovery is yet.

**Comment by pongad** [comment]
We haven't started. Regular codegen is formatted by the pipeline, not by toolkit itself. Discovery is using its own pipeline, so it doesn't benefit from gofmt yet.

**Comment by pongad** [comment]
Resolved by change in internal tooling: gofmt before packaging.

**Comment by broady** [comment]
@pongad got a link to the CL? I'd like to take a look.
