### ISSUE TITLE
Remove path structs from go codegen

### ISSUE THREAD

**Issue by saicheems** [googleapis/toolkit#67]
Instead of generating types and methods for parsing/generating resource names, produce functions analogous to other languages.

ex (via @jba):
```
func ParseProjectPath(path string) (string, error) { return gax.SplitPath1(path)  }
func ProjectPath(projectName string) string { return "projects/" + projectName }

func ParseLogPath(string path) (string, string, error) { return gax.SplitPath2(path) }
func LogPath(projectName, logName string) string { return "projects/" + projectName + "/logs/" + logName) }
```

**Comment by jba** [comment]
Or do nothing, until people ask for this.

Or make this a codegen parameter, off by default. Turn it on for APIs where it's actually useful.
