### ISSUE TITLE
Use "Client" as GAPIC generated class name

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#670]
Currently we use `Api` suffix for class name. So gRPC service name is `Library`, the generated class is `LibraryApi`.

Internally we got feedback to rename this. Probably `Client` is fine, so `LibraryClient`?

- [x] C#
- [x] Go
- [x] Java
- [x] NodeJS
- [x] PHP
- [x] Python
- [x] Ruby

**Comment by jmuk** [comment]
Assigning @swcloud for triaging.

Cc: @bjwatson 

Also cc @blowmage @quartzmo this could potentially mean regenerating files in google-cloud-ruby.

**Comment by jmuk** [comment]
Additionally, we don't like `Service` suffixes on multiple service definitions (like `TraceService` service in trace API or `LoggingServiceV2` service in logging API). We may want to do what Golang do -- removing such common patterns, so that it would be `TraceClient` instead of `TraceServiceClient`.

This is not a part of the internal feedback, but just my personal feeling.

**Comment by bjwatson** [comment]
Let's wait for feedback from @anthmgoogle before proceeding.

**Comment by anthmgoogle** [comment]
The revised plan was to standardize on <ServiceName>Client for all 7 languages.

**Comment by bjwatson** [comment]
I added checkboxes for all the languages. IIUC, this has already been done for Go, correct @pongad and @jba?

**Comment by pongad** [comment]
Go has been using "Client" since day 1 (well, close enough). I'll mark Go done.

**Comment by bjwatson** [comment]
Thanks @pongad!

**Comment by anthmgoogle** [comment]
C# is also done. Java, Python, NodeJS, Ruby and PHP need to be changed.

**Comment by bjwatson** [comment]
Thanks @anthmgoogle. I've checked the C# box.

**Comment by jmuk** [comment]
not closed fully :wink:

**Comment by garrettjonesgoogle** [comment]
Java done.

**Comment by jmuk** [comment]
Node.JS done.

**Comment by michaelbausor** [comment]
PHP done

**Comment by michaelbausor** [comment]
All languages done - closing
