### ISSUE TITLE
Enum object is not emitted in Node.js code

### ISSUE THREAD

**Issue by jmdobry** [googleapis/toolkit#705]
See GoogleCloudPlatform/google-cloud-node#1761 for reference.

@jmuk PTAL

**Comment by jmuk** [comment]
I see, this is a bug of referring to a message in the sample code. This should be `monitoringV3.ListTimeSeriesRequest.TimeSeriesView`.

**Comment by jmdobry** [comment]
Yes, it's in the proto: https://github.com/googleapis/googleapis/blob/master/google/monitoring/v3/metric_service.proto#L196

The string `ListTimeSeriesRequest` doesn't appear anywhere in the generated Node.js code.
