### ISSUE TITLE
Invalid XML comments in C#

### ISSUE THREAD

**Issue by jskeet** [googleapis/toolkit#72]
Two issues in the generated code at the moment, only in the logging API:

- References to `LoggingServiceV2Client.ListMonitoredResourceDescriptors` which doesn't exist - I'm not sure why we're not generating that method.

- Unclosed `see` references: `There are no RPC <see cref="StatusCode">s eligilbe for retry for "NonIdempotent" RPC methods.` (That also has a typo in "eligilbe".)

Assigning to Chris to start with, but I hope I could fix the second one myself....

**Comment by chrisdunelm** [comment]
This was fixed a while ago.
