### ISSUE TITLE
Add formatted string type references for all desired languages

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#736]
Currently getStringFormatExample is implemented only for Java and Node.js, but is probably desired in all languages except Go (as references to supporting libraries would require additional words).

**Comment by eoogbe** [comment]
@tcoffee-google Is this still relevant?

**Comment by eoogbe** [comment]
@jskeet @vam-google @lukesneeringer @geigerj Is this still relevant to your languages?

**Comment by jskeet** [comment]
I don't know the context here. @chrisdunelm might.

**Comment by chrisdunelm** [comment]
I also don't know the context. Where is `getStringFormatExample` defined? I expected to see it in [SurfaceNamer.java](https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/transformer/SurfaceNamer.java), but it doesn't appear to be there.

**Comment by geigerj** [comment]
I am also unsure what `getStringFormatExample` refers to.

**Comment by eoogbe** [comment]
I'm going to assume this is obsolete if it can't be found in the codebase
