### ISSUE TITLE
Consider making name prefix stripping more aggressive

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#759]
Currently name prefix stripping works by deleting the prefix if the prefix is the same as the package name. For example, if the name of the package is "library", then we'd call the client "Client" instead of "LibraryClient".

This is arguably not aggressive enough. If we have a package "foo", we might have a type "FooBarClient". Typing "foo.FooBarClient" still causes stutter. 

One way out is to change the logic so that it works more like `strippedPrefix = strings.TrimPrefix(prefix, packageName)`. In this way, we will end up with "foo.BarClient".

@vkedia @jba

**Comment by jba** [comment]
I like that, as long as there is a way to override if there is a conflict.

**Comment by pongad** [comment]
I have thought about this more. While it would make the surface nicer, I don't think we are prepared to deal with potential cost.

In some ways, this is similar in spirit to https://github.com/googleapis/toolkit/issues/486.

Naively, both `foo.FooBarClient` would become `foo.BarClient`. This is a problem if the same package defines `BarClient` elsewhere. This conflict is not hard to resolve: We just have to make sure to look for `BarClient` before we rename.

The problem with backward compatibility is more complicated. `BarClient` might be added after we've already renamed. In that scenario, we cannot rename the existing `BarClient` back to `FooBarClient` as it would break users. Our only choice would be to name `BarClient` something else. This renaming will probably be some kind of config, and Go would be the only consumer.

Additionally, I think this shortening will have limited use. The only times the user will benefit from the short name is creating a new client and writing down the client's type. I believe most users do not need to do this frequently.

@jba Please let me know what you think.

**Comment by jba** [comment]
Agreed; let's not do it.
