### ISSUE TITLE
Feature request: MetadataGen config input

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#780]
Original discussion: https://github.com/googleapis/toolkit/pull/778#issuecomment-262612735

From @garrettjonesgoogle:

> I wonder if it would be more maintainable to have the tool understand the same config that artman does. As it is now, for every new config line we put in artman config, we have to add a new command line option to the tool. I doubt anyone is going to handcraft the full command line for this tool.

I'm not opposed to having MetadataGen read YAML as input (as it already does for the existing packman config files). But what does this mean for how the artman config is consumed? Is it consumed once in whole by `artman`, where it is merged from several YAML files, and once additionally in part by `MetadataGen`, where just the `artman_{API}.yaml` file is read in? That seems to complicate the logic somewhat, and it means that MetadataGen doesn't benefit from `artman`'s built-in config merging and per-language section selection logic.

**Comment by garrettjonesgoogle** [comment]
One option is to have artman perform the merging logic and create a temporary merged yaml file to pass to `MetadataGen`.

**Comment by geigerj** [comment]
Having artman create a temporary merged yaml SGTM.
