### ISSUE TITLE
Remove JDK 8 features

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/toolkit#8]
FYI: @jskeet 

We just enabled travis, but it is failing with compile errors because of Java8 syntax in the CSharpGapicContext.java. As agreed, we'd like to keep the codebase jdk7 clean, it'd be nice to get that fixed ASAP.

**Comment by jskeet** [comment]
@chrisdunelm can you look at this?

**Comment by chrisdunelm** [comment]
PR#9 done, but travis is still failing.
It looks like it's now failing for the same reasons on JDK7 and JDK8, so this failure is probably unrelated to this issue.

**Comment by pongad** [comment]
I believe this is due to the framework's TestConfig not being able to find protoc properly. Can anyone confirm this? If this is the case we should move this into its own issue.

**Comment by jmuk** [comment]
I've confirmed that, filed #11 separately.

**Comment by tbetbetbe** [comment]
This was fixed by #9
