### ISSUE TITLE
Dummy Python message classes contain extraneous data, imports

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#804]
### What
A proto message is "transitively referenced" by an API if there is some method of the API whose request or response message contains a field whose type is, or whose type transitively references that proto message. `ProtoFileView` compiles the proto files containing all such transitiviely referenced proto types.

However, the proto files may also contain other messages and imports that are _not_ transitively referenced by the API. We should not generate Python docs or imports for these messages.

### Why
The imports are broken if they point to files that are not contained in the `ProtoFileView` (since we do not generate their corresponding dummy Python module), causing Sphinx doc generation to fail.

The extraneous messages don't break anything, but they're irrelevant and may themselves contain broken links (if they link to files not contained in the `ProtoFileView`), so they should be excluded as well.

**Comment by geigerj** [comment]
@lukesneeringer

**Comment by eoogbe** [comment]
Closing because these classes do not appear to exist any longer.
