### ISSUE TITLE
Find a way to keep toolkit and compilecheck in sync

### ISSUE THREAD

**Issue by pongad** [googleapis/toolkit#84]
Ideally all of the discovery files we have in testdata should always pass compilecheck. We should find a way to enforce this.

**Comment by bjwatson** [comment]
@pongad Is this Discovery-specific?

**Comment by pongad** [comment]
@bjwatson It is. Added the label. In this case, "compilecheck" refers to the tool we wrote to make sure discovery samples compile.

**Comment by bjwatson** [comment]
Ok, thanks.

**Comment by saicheems** [comment]
This is a duplicate of other bugs... and is being implemented
