### ISSUE TITLE
Correctly handle IAM resource name types

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#843]
We need to handle resource name types on IAM methods. These should probably accept generic ResourceName objects, as IAM methods will usually accept many resource name formats. Toolkit needs to support specifying ResourceName objects as flattened method parameters without interferring with the string format functions used by other languages.

**Comment by jskeet** [comment]
I think this is now completely done, isn't it? Suggest closing.

**Comment by michaelbausor** [comment]
Yes, this is complete.
