### ISSUE TITLE
Request object method incompatible with streaming

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#850]
It should be an error to specify request_object_method as true for a streaming method

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by eoogbe** [comment]
Is this the case for server streaming or client streaming?

**Comment by michaelbausor** [comment]
This is true for bidi and client streaming. For server streaming, I think a case can be made for specifying this field, because a server streaming method can support a flattened signature.
