### ISSUE TITLE
Remove ALL_SCOPES from individual service .js file

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#868]
Historically, `ALL_SCOPES` is defined in each service js file and `index.js` integrates them into a single `ALL_SCOPES` there.

When `index.js` is generated by the toolkit, it does not have to follow the same structure anymore. Simply `index.js` can list up the all scopes.

**Comment by eoogbe** [comment]
@lukesneeringer Can you add a priority?

**Comment by eoogbe** [comment]
Duplicate ##1100
