### ISSUE TITLE
Go well-known proto types should not be vendored

### ISSUE THREAD

**Issue by jba** [googleapis/toolkit#88]
The following google.protobuf types can be imported from github.com/golang/protobuf/ptypes/_subdir_. E.g. for Any, use github.com/golang/protobuf/ptypes/any.

Any, Duration, Timestamp, Struct, Empty

Also, the wrappers FloatValue, DoubleValue, etc. are in github.com/golang/protobuf/ptypes/wrappers.

The import path may change, but for now I suggest we use it.

**Comment by saicheems** [comment]
I've figured out how to do this and it's been implemented.
Definitely not scalable... but it's there.
