### ISSUE TITLE
Exclude *pyc from MANIFEST.in

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#892]
### What

`*pyc` files should not be included in packages.

### Why

See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2913 for context. Will do this after https://github.com/googleapis/toolkit/pull/870 is merged.

### How

Add the following line in the correct position:

```diff
--- MANIFEST.in.old	2017-01-03 16:47:43.000000000 -0800
+++ MANIFEST.in	2017-01-03 16:18:10.000000000 -0800
@@ -1,4 +1,5 @@
 include README.rst LICENSE
 global-include *.json
 graft google
+global-exclude *.pyc
 prune .tox
```

**Comment by lukesneeringer** [comment]
@geigerj Maybe sure to exclude `__pycache__` as well.

**Comment by geigerj** [comment]
@lukesneeringer Do you know what the syntax for excluding `__pycache__` is? It's not clear to me how to exclude all subdirectories of a particular name from the [MANIFEST.in docs](https://docs.python.org/2/distutils/sourcedist.html#commands). (`global-exclude **/__pycache__/**`?)

**Comment by lukesneeringer** [comment]
No clue!

Django did [this](https://github.com/django/django/blob/master/MANIFEST.in#L16-L17). I assume they know? :-p

**Comment by lukesneeringer** [comment]
LGTM.
