### ISSUE TITLE
Use 2017 in license header in the new files.

### ISSUE THREAD

**Issue by shinfan** [googleapis/toolkit#897]
Happy new year!

**Comment by garrettjonesgoogle** [comment]
Only new files should be updated. Existing files should retain the year that they were created.

**Comment by saicheems** [comment]
Btw, the license check will fail if you do this...
I have a fix ready in a different PR, but I'll split it into another CL now so nobody else has to redo my work.

**Comment by garrettjonesgoogle** [comment]
Is this taken care of now?

**Comment by shinfan** [comment]
Yes, this should be fixed.
