### ISSUE TITLE
API Explorer URL could be incorrect in docs

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#933]
Some docs link to the API's apis-explorer page, e.g., https://github.com/googleapis/toolkit/blob/65b58941abcef1426b35cf801762db37e1ad9ebc/src/test/java/com/google/api/codegen/testdata/python_doc_README_library.baseline#L11

This URL is actually formed using the discovery doc name in the path. In most cases, this will be the same as the first segment in the API `name` configured in the service config. (For example, Pub/Sub has `name`==`pubsub.googleapis.com` and discovery doc name `pubsub`.) However, this discovery doc name is override-able internally via the service config. The part of the service config that allows this override is not available externally.

We should either open source this aspect of api-compiler, or reflect the override in the gapic config. Marking this as low priority since we haven't seen any cases of this override in practice.

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.
