### ISSUE TITLE
Implement getEnumValue on each language's ModelTypeNameConverter

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#944]
Related to #941, by specifying initial value for encoding, like `config.encoding=FLAC`, it ends up be an error `java.lang.UnsupportedOperationException: getEnumValue not supported by NodeJS.` It succeeds without the title, although the initial value is `ENCODING_UNSPECIFIED` which isn't great. This method should be implemented before we're going to add the config.

Affects C#, Go, NodeJS, PHP, and Ruby.

**Comment by jmuk** [comment]
@eoogbe -- can you take a look at this?

**Comment by jmuk** [comment]
Note: related issue is https://github.com/googleapis/googleapis/issues/243 -- this is necessary to support config like https://github.com/jmuk/googleapis/commit/4626f929b08b24b3859f3db0c4242bf54021de59

**Comment by eoogbe** [comment]
Just to make sure I have the syntax right, given:
```
// myproto.proto
service Gopher {
  rpc SimpleMethod(SimpleRequest) returns (SimpleResponse);
}
message SimpleRequest {
  enum Alignment {
    GOOD = 0;
    EVIL = 1;
  }
  Alignment alignment = 1;
}
message SimpleResponse {
  string value = 1;
}
```

the output for the GOOD Alignment should be:
C#: `SimpleRequest.Types.Alignment.Good`
Go: `*myprotopb.SimpleRequest_GOOD`
NodeJS: `gopherV1.SimpleRequest.Alignment.GOOD`
PHP: `Alignment::GOOD`
Ruby: `Alignment::GOOD`

**Comment by jmuk** [comment]
for NodeJS, that's right.

To be more precisely, let's say this is for some Foo API with package name `google.foo.v1`. In that case NodeJS is `fooV1.SimpleRequest.Alignment.GOOD`.

@chrisdunelm @pongad @michaelbausor @swcloud could you review?

**Comment by chrisdunelm** [comment]
For C# that's correct.

**Comment by jmuk** [comment]
@lukesneeringer @bjwatson @geigerj FYI in case this will affect Python soon

**Comment by geigerj** [comment]
@jmuk Acknowledged. Note that Python is somewhat different from other languages in that we generate an alias file for the enums (e.g., [here](https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/python_enum_library.baseline)), and the equivalent Python code should probably refer to that file rather than to the generated gRPC code.

**Comment by pongad** [comment]
According to the [generated code guide](https://developers.google.com/protocol-buffers/docs/reference/go-generated#enum), this is correct for Go

**Comment by jmuk** [comment]
oops, seems @michaelbausor is out of office. @garrettjonesgoogle, do you have some insights for PHP? (See @eoogbe's comment above).

**Comment by garrettjonesgoogle** [comment]
The PHP one looks correct based on my analysis.
