### ISSUE TITLE
package generator should respect 'skip_packman' config (or whatever it's named)

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#950]
The artman config contains 'skip_packman' flag to control the invocation of packman. Since several functionalities for packman have been migrated into toolkit's package generator, I think it makes more sense to suppress package generator with some configs -- otherwise I'll see rewriting of package.json or README for Node.

BTW `skip_packman` isn't the right name to configure this. I've filed https://github.com/googleapis/artman/issues/111 once in a while, this issue will be related.

Cc: @shinfan @geigerj

**Comment by geigerj** [comment]
I would support renaming `skip_packman` to `generate_package_metadata` (which has the opposite meaning and defaults to True) and adding this field to [the package config](https://github.com/googleapis/artman/blob/master/pipeline/tasks/package_metadata_tasks.py#L42).

**Comment by eoogbe** [comment]
@geigerj Can you add a priority?

**Comment by geigerj** [comment]
To my knowledge this is obsolete. @lukesneeringer are there any existing cases where toolkit should *not* generate package metadata for NodeJS? If there are, please re-open.
