### ISSUE TITLE
The Copyright header of the generated code is still 2016

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#968]
https://github.com/googleapis/toolkit/tree/master/src/test/java/com/google/api/codegen/testdata

All of the baseline files have the "Copyright" header comments, but all of them are still 2016. Should we at least update the header to 2017?

**Comment by garrettjonesgoogle** [comment]
When we fix this, we might as well do https://github.com/googleapis/toolkit/issues/874 at the same time (put "All rights reserved" it title case, "All Rights Reserved").
