### ISSUE TITLE
Integrate correctness checking with sample generator

### ISSUE THREAD

**Issue by tcoffee-google** [googleapis/toolkit#995]
Currently, correctness checking for generated samples is done by code separate from the sample generator, in a process separate from sample generation (now referred to as "compile check"). This code does not execute the sample code, but instead either compiles the samples against client libraries (for compiled languages), or compares certain variable types made explicit in the samples against client library documentation (for interpreted languages). Moreover, this code is written in a different language (Go) from the sample generator (Java), obstructing any integration of these processes.

Substantial limitations of this approach have been understood from the beginning:

1. Correctness checks are not made as part of tests of the sample generator, necessitating a separate manual process for updates affecting sample content.

2. Samples are not tested for proper execution or (for interpreted languages) even syntax: for instance, bugs and concerns have been noticed in samples' implementations of page-streaming loops whose behavior escaped detection or explicit definition in tests. In interpreted languages, elementary syntax errors have crept into generated samples prior to human detection.

3. Checkers cannot access functionality of the sample generator toolkit to generate correctness-checking code in supported languages. At the highest level, it cannot leverage the powerful snippet engine used to write readable templates, instead relying on a separate, poorly readable templating language from the Go standard library. At the lowest level, it cannot access generator information like names of variables that have been renamed to avoid name collisions, an outstanding correctness issue that could only be addressed within this approach through substantial duplication of functionality.

4. Checkers for interpreted languages rely on fragile regular expression parsing to extract relevant information for type checking (in the absence of actual code execution). As a result, even tiny cosmetic updates to generated samples require corresponding changes in checkers to continue functioning --- changes which may not be readily predictable (for instance, changes in line breaking). More significant changes can be tricky to accommodate, due to the poor match between regex parsing and the structure of samples in various languages.

Instead, correctness checking should follow a more straightforward and more robust approach: For each generated sample, the sample generator uses its existing backend and snippet engine, with a different template file, to generate a corresponding file in the target language containing a mock of the corresponding method, against which the entire sample can be executed. The generator toolkit then runs additional tests to confirm successful execution of samples against these mocks. For interpreted languages, the construction of the mock may still rely on parsing data from client library documentation, unless client library generator logic is sufficiently well understood to obviate this aspect of correctness checking. This approach can overcome all the limitations described above.

**Comment by tcoffee-google** [comment]
@vchudnov-g @saicheems

**Comment by garrettjonesgoogle** [comment]
The overall approach seems sensible, but in terms of where the checking is executed - I don't want the capability of executing all 7 languages to live in toolkit.

**Comment by tcoffee-google** [comment]
I think I've suggested this before, but never really discussed: what if we were to make these tests separate Gradle tasks so that they don't run with `gradlew build`, but the samplegen team could run, say, `gradlew build check` to enable them?

**Comment by garrettjonesgoogle** [comment]
So we want to enable running of tests for all 7 languages on https://github.com/googleapis/api-client-staging . I don't really want the work repeated between toolkit and api-client-staging. I don't know if this means you should add samplegen output to api-client staging, or if you should create a distinct samplegen output repository and implement shared tools/plugins that they can both use (my preferred solution), but I really don't think toolkit itself is the right place.

**Comment by tcoffee-google** [comment]
Though the README is out of date (there is no "/generated/tests"), it looks to me as though api-client-staging still assumes that the setup to test in 7 languages is established on the local machine. What work is it that would be repeated?

**Comment by vchudnov-g** [comment]
We came up with a  plan for run-time checking earlier, and decided on synthetic APIs so we would test against code output by real library generators. We haven't gotten around to implementing it. Let's circle back on that with the current architecture....but let's be mindful of our priorities with upcoming work.

**Comment by saicheems** [comment]
Not sure if we have the development bandwidth for this item anymore :(

**Comment by tcoffee-google** [comment]
I would leave this as P1, coming next after https://github.com/googleapis/toolkit/issues/587, because otherwise we still leave considerable room for bugs in sample correctness. I would say that the synthetic API concept partially overlaps the proposal here.

**Comment by vchudnov-g** [comment]
Demoting to P2 due work priorities, not that this wouldn't be important to have.
